### ISSUE TITLE
/rb sum gem not working

### ISSUE THREAD

**Issue by madScripting** [raethkcj/RatingBuster#1]
The following commands give a LUA error:
/rb sum gem sumgemred
/rb sum gem sumgemyellow
/rb sum gem sumgemblue

Adding the gem to the command (by link or by itemID) for example "/rb sum gem sumgemred [Solid Zircon]" results in the message:
RatingBuster: Queried server for Gem: Solid Zircon. Try again in 5 secs.

If the itemID is used instead of the linked item, for example for example "/rb sum gem sumgemred 28463" it will give the message:
RatingBuster: Queried server for Gem: 28463. Try again in 5 secs.

**Comment by raethkcj** [comment]
Should be fixed now, you will still need to enter gems twice if your game doesn't have them cached, but it should no longer get stuck.
