### ISSUE TITLE
[Bug]: Dont have spellpower with 1.5.10

### ISSUE THREAD

**Issue by jebo80** [raethkcj/RatingBuster#101]
### Describe the bug

I loaded the last update but i dont have spellpower. 

### Addon Source

GitHub Releases

### Version

1.5.10

### Locale

German

### Talent Specialization

Discipline Priest

### Race

Human

**Comment by raethkcj** [comment]
Can you reload, type `/sldebug`, then mouse over an item with spellpower and paste the results here?

**Comment by jebo80** [comment]
Hi, when i type /sldebug nothing happen...

**Comment by jebo80** [comment]
I have 2 screenshots for you, perhaps they help? 

First is a item with spellpower "Zaubermacht" and second is the list in which is also no spellpower...

Sorry for my bad english

![3f0a744c5324955d0bf585753875981b](https://user-images.githubusercontent.com/114264088/192112148-df15661c-3e9b-4ba8-a80b-7b34929ec786.png)
![fb6332a6e958f2d47badb8cfb2e7ff53](https://user-images.githubusercontent.com/114264088/192112149-4b7c5cf5-3f31-49a6-bb56-13dfeb1c0249.png)

**Comment by jebo80** [comment]
And here is a third screenshot... 

We have spell damage ( Zauberschaden ) and healing ( Heilung ) but no spellpower ( Zaubermacht )

![847f32719b5aa2cc672dc812568f47fc](https://user-images.githubusercontent.com/114264088/192116505-fa909e76-6633-4483-9b3c-5cbfee16d272.png)

**Comment by raethkcj** [comment]
This is intentional. You should choose the stat you are interested in, or both. The intention is to reflect the stats you gain on your character sheet, which are still separated into Damage and Healing:

![image](https://user-images.githubusercontent.com/7716908/192117541-b92c9f7d-01e8-4e4b-b33c-b30fecd232f1.png)
