### ISSUE TITLE
[Bug]: Compare items blink

### ISSUE THREAD

**Issue by zdinch** [raethkcj/RatingBuster#103]
### Describe the bug

Hello! Thanks for keeping Ratingbuster since the last version when comparing items the tooltip blinks, I have tried the previous version and it works fine.

Thank you very much and sorry for my english!

### Addon Source

WowUp

### Version

1.5.10

### Locale

English

### Talent Specialization

Enhancement Shaman

### Race

Orc

**Comment by raethkcj** [comment]
This is almost definitely related to the option I added to hide Blizzard's stat comparisons. I can't reproduce the issue myself yet, but if you want to be on the latest version, you can probably workaround it by disabling this option for now:

https://i.imgur.com/zENCJ1j.png

**Comment by zdinch** [comment]
Hello! I have tried to disable "Hide Blizzard Item Comparisons" with the latest version and it no longer blinks, thanks!

**Comment by dmc1793** [comment]
Can confirm that the blizzard item compare window still blinks even with Rating Buster as the only addon. Workaround atm is to just not hide the blizzard item compare.

**Comment by zdinch** [comment]
If I have tried it only with Ratingbuster and it blinks.

**Comment by boktai1000** [comment]
Coming here to confirm that I noticed this as well today when comparing the flickering / blinking. Double checked and only happens with RatingBuster enabled.

**Comment by raethkcj** [comment]
FWIW I was able to figure out how to reproduce it, working on potential fix but it's surprisingly complex to get right.
