### ISSUE TITLE
[Bug]: Numerous errors

### ISSUE THREAD

**Issue by Quizzus** [raethkcj/RatingBuster#104]
### Describe the bug

At some point Rating Buster stopped working for me giving these logs (and also massive lag):
---------------------------------------------------------------------------------------------------------------------------------------------
Message: Interface\AddOns\StatLogic\StatLogic.lua:1260: Attempt to register unknown event "GLYPH_ADDED"
Time: Sun Sep 25 11:08:23 2022
Count: 1
Stack: Interface\AddOns\StatLogic\StatLogic.lua:1260: Attempt to register unknown event "GLYPH_ADDED"
[string "=[C]"]: in function `?'
[string "@Interface\AddOns\StatLogic\StatLogic.lua"]:1260: in main chunk

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "GLYPH_ADDED"

---------------------------------------------------------------------------------------------------------------------------------------------
Message: Interface\AddOns\RatingBuster\RatingBuster.lua:1346: attempt to call method 'GetOrderedTalentInfo' (a nil value)
Time: Sun Sep 25 11:08:24 2022
Count: 1
Stack: Interface\AddOns\RatingBuster\RatingBuster.lua:1346: attempt to call method 'GetOrderedTalentInfo' (a nil value)
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:1346: in function <Interface\AddOns\RatingBuster\RatingBuster.lua:1330>

Locals: (for generator) = <function> defined =[C]:-1
(for state) = <table> {
 MOD_INT = <table> {
 }
 ADD_DODGE = <table> {
 }
 ADD_MANA_REG_MOD_NORMAL_MANA_REG = <table> {
 }
 MOD_ARMOR = <table> {
 }
 MOD_STA = <table> {
 }
 MOD_STR = <table> {
 }
}
(for control) = "ADD_MANA_REG_MOD_NORMAL_MANA_REG"
statMod = "ADD_MANA_REG_MOD_NORMAL_MANA_REG"
cases = <table> {
 1 = <table> {
 }
}
add = "MANA_REG"
mod = "NORMAL_MANA_REG"
sources = ""
firstSource = true
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
}
(for control) = 1
_ = 1
case = <table> {
 tab = 3
 num = 6
 rank = <table> {
 }
}
source = ""
(*temporary) = nil
(*temporary) = <table> {
 tip = StatLogicTooltip {
 }
 tipMiner = StatLogicMinerTooltip {
 }
 GetNormalManaRegenFromSpi = <function> defined @Interface\AddOns\StatLogic\Vanilla_Logic.lua:45
 GetClassIdOrName = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:389
 GenericStatMap = <table> {
 }
 argCheck = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:77
 GetRatingIdOrName = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:501
 StatTable = <table> {
 }
 StatModTable = <table> {
 }
 StatModInfo = <table> {
 }
 GetStatNameFromID = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:393
}
(*temporary) = 3
(*temporary) = 6
(*temporary) = "attempt to call method 'GetOrderedTalentInfo' (a nil value)"
pairs = <function> defined =[C]:-1
StatLogic = <table> {
 tip = StatLogicTooltip {
 }
 tipMiner = StatLogicMinerTooltip {
 }
 GetNormalManaRegenFromSpi = <function> defined @Interface\AddOns\StatLogic\Vanilla_Logic.lua:45
 GetClassIdOrName = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:389
 GenericStatMap = <table> {
 }
 argCheck = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:77
 GetRatingIdOrName = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:501
 StatTable = <table> {
 }
 StatModTable = <table> {
 }
 StatModInfo = <table> {
 }
 GetStatNameFromID = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:393
}
class = "DRUID"
ipairs = <function> defined =[C]:-1
addStatModOption = <function> defined @Interface\AddOns\RatingBuster\RatingBuster.lua:1307
defaults = <table> {
 global = <table> {
 }
 profile = <table> {
 }
}
profileDB = nil
options = <table> {
 args = <table> {
 }
 type = "group"
 set = <function> defined @Interface\AddOns\RatingBuster\RatingBuster.lua:98
 get = <function> defined @Interface\AddOns\RatingBuster\RatingBuster.lua:91
}
f = <unnamed> {
 0 = <userdata>
}

### Addon Source

WowUp

### Version

1.5.12

### Locale

Russian

### Talent Specialization

Feral Druid

### Race

Tauren

**Comment by raethkcj** [comment]
Sorry about that, with the Wrath launch I haven't been testing on Classic Era / Season of Mastery. Should be fixed now, thanks for reporting!

**Comment by Quizzus** [comment]
Thanx for such a quick fix, it works now, but still some mistakes are present:

Message: Interface\AddOns\StatLogic\Vanilla_Logic.lua:57: attempt to perform arithmetic on field '?' (a nil value)
Time: Sun Sep 25 17:45:45 2022
Count: 1
Stack: Interface\AddOns\StatLogic\Vanilla_Logic.lua:57: attempt to perform arithmetic on field '?' (a nil value)
[string "@Interface\AddOns\StatLogic\Vanilla_Logic.lua"]:57: in function `GetNormalManaRegenFromSpi'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:2125: in function <Interface\AddOns\RatingBuster\RatingBuster.lua:1764>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:1727: in function `ProcessLine'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:1605: in function `handler'
[string "@Interface\AddOns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetInventoryItem'
[string "@Interface_Vanilla\FrameXML\PaperDollFrame.lua"]:818: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: self = <table> {
 GetRAPFromAgi = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1823
 GetReductionFromArmor = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1412
 GetSum = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:2315
 argCheck = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:77
 GetRAPPerAgi = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1784
 GetStatMod = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1378
 tip = StatLogicTooltip {
 }
 GetFinalArmor = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:2757
 GetClassIdOrName = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:389
 GetRatingIdOrName = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:501
 GetStatNameFromID = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:393
 StatModInfo = <table> {
 }
 RemoveEnchant = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:2086
 GetBlockValuePerStr = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1626
 GetAPFromAgi = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1746
 GetSpellCritFromInt = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:2007
 GetDiff = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:3002
 GetAPPerAgi = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1704
 StatModTable = <table> {
 }
 GetHealthRegenFromSpi = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:2066
 GetEffectFromRating = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1501
 StatTable = <table> {
 }
 GetNormalManaRegenFromSpi = <function> defined @Interface\AddOns\StatLogic\Vanilla_Logic.lua:45
 GetBlockValueFromStr = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1665
 PatternTest = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:3118
 Bench = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:3098
 GenericStatMap = <table> {
 }
 GetGemID = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:2219
 GetAPPerStr = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1547
 GetDodgePerAgi = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1892
 tipMiner = StatLogicMinerTooltip {
 }
 GetEffectFromDefense = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1439
 BuildGemmedTooltip = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:2129
 RemoveGem = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:2090
 GetOrderedTalentInfo = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1334
 GetAPFromStr = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1583
 RatingExists = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1452
 GetDodgeFromAgi = <function> defined @Interface

**Comment by raethkcj** [comment]
Oof, fixed again.

**Comment by Quizzus** [comment]
Works perfectly, thank you so much!
