### ISSUE TITLE
[Bug]: Is druid attack power calculating correctly?

### ISSUE THREAD

**Issue by OnceWasPerfect** [raethkcj/RatingBuster#107]
### Describe the bug

I was trying to decide between the Dragonfriend Bracers and the Deadly Gladiator's Armwraps of Triumph and the difference in Power that the character screen reports and what Rating Buster reports are different.  I may have a setting wrong or something but I couldn't figure it out.  The character sheet reports my attack power with Dragonfriend Bracers on as 6370 and when I swap them for the PVP bracers it shows 6278, a difference of 92.  Rating Buster shows that there should be a Feral Attack Power difference of 48 and an Attack Power difference of 38.6.  Neither of those are correct if i'm only supposed to use one and added together they are only 86.6.  Then I thought maybe it's the difference in Agility 67.7 vs 59.3 which is 8.4 but when you add that to the 86.6 you get 95 more than the 92 the character sheet shows.  I've attached some screenshots.  Notice I have ignore enchants set so that shouldn't be affecting it.  

PS:  When in caster form my character sheet shows my AP as 2114 with the Dragonfriend Bracers and 2022 with the PVP bracers, a different of 92.  Rating Buster shows a Feral AP difference of 51.4 and an AP difference of 42.8.

![feral1](https://user-images.githubusercontent.com/53492647/193720734-c443182c-cf46-4d8a-8acf-51e36d519f3e.png)
![feral2](https://user-images.githubusercontent.com/53492647/193720736-5e8e2962-1f82-412d-89d9-d328d13d0bea.png)
![feral3](https://user-images.githubusercontent.com/53492647/193720738-d1e3f4c0-e07d-4617-b59c-1db06c76561e.png)

### Addon Source

GitHub Releases

### Version

1.5.14

### Locale

English

### Talent Specialization

Feral Druid

### Race

Tauren

**Comment by raethkcj** [comment]
I don't have time for a full fix just now, but I can confirm it is bugged and about 20% too high. Thanks.

**Comment by OnceWasPerfect** [comment]
Awesome thank you, for my own knowledge when comparing items as a feral should I be using both the regular Attack Power and Feral Attack Power in ratingbuster or is Feral Attack Power supposed to take all that into account?

**Comment by raethkcj** [comment]
When working correctly, Feral Attack Power should be all you need. The intention is to show how much AP an item *will* give you in form, since agi doesn't give druids AP unless in cat form.

**Comment by raethkcj** [comment]
Feral Attack Power is intended to take that into account. Honestly this is pretty unclear and I think I'd like to rework it into separate "Cat Form Attack Power" and "Bear Form Attack Power" as right now it's trying to do both and succeeding at neither.

**Comment by OnceWasPerfect** [comment]
Awesome, thank you for the info.  What you describes sounds like it would be great, in the mean time I understand what ratingbuster is telling me a bit better.  Thanks!

**Comment by raethkcj** [comment]
It turns out that several of the problems here were caused by trying to predict Feral AP while not in forms, and ultimately there's not a good way to solve them in a way that makes sense for everyone without bringing in an external addon like [RatingBuster AlwaysBuffed](https://www.curseforge.com/wow/addons/ratingbuster-alwaysbuffed/files), which hasn't been ported to Classic.

Therefore, I've simply removed Feral AP as its own Summary line, and instead Druids should use the regular Sum AP, which will show the actual current AP provided by an item in their current form.
