### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by I3igAl** [raethkcj/RatingBuster#108]
### Describe the bug

Dont know what is causing it but on my second account StatLogic is throwing massive errors when i mouseover anything equippable. mainly flooding me when mousing quest rewards to find the most valuable vendor gold.

1513x StatLogic\Wrath_Logic.lua:3742: attempt to perform arithmetic on field '?' (a nil value)
[string "@StatLogic\Wrath_Logic.lua"]:3742: in function `GetAvoidanceAfterDR'
[string "@StatLogic\Wrath_Logic.lua"]:3778: in function `GetAvoidanceGainAfterDR'
[string "@RatingBuster\RatingBuster-1.5.8.nil.lua"]:2923: in function `MELEE_HIT_AVOID'
[string "@RatingBuster\RatingBuster-1.5.8.nil.lua"]:2947: in function `func'
[string "@RatingBuster\RatingBuster-1.5.8.nil.lua"]:3379: in function `StatSummary'
[string "@RatingBuster\RatingBuster-1.5.8.nil.lua"]:1683: in function `handler'
[string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:107: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105>
[string "=[C]"]: in function `SetInventoryItem'
[string "@Interface_Wrath\FrameXML\PaperDollFrame.lua"]:1621: in function `oldPaperDollItemSlotButton_OnEnter'
[string "@ItemRack\ItemRack-3.69.nil.lua"]:1724: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
self = <table> {
 GetRAPFromAgi = <function> defined @StatLogic\StatLogic.lua:1832
 GetReductionFromArmor = <function> defined @StatLogic\StatLogic.lua:1421
 GetSum = <function> defined @StatLogic\StatLogic.lua:2324
 argCheck = <function> defined @StatLogic\StatLogic.lua:77
 GetDodgeChanceBeforeDR = <function> defined @StatLogic\Wrath_Logic.lua:3603
 GetRAPPerAgi = <function> defined @StatLogic\StatLogic.lua:1793
 GetStatMod = <function> defined @StatLogic\StatLogic.lua:1387
 tip = StatLogicTooltip {
 }
 GetFinalArmor = <function> defined @StatLogic\StatLogic.lua:2766
 GetClassIdOrName = <function> defined @StatLogic\StatLogic.lua:389
 GetRatingIdOrName = <function> defined @StatLogic\StatLogic.lua:501
 GetStatNameFromID = <function> defined @StatLogic\StatLogic.lua:393
 StatModInfo = <table> {
 }
 GetAvoidanceGainAfterDR = <function> defined @StatLogic\Wrath_Logic.lua:3761
 GetAvoidanceAfterDR = <function> defined @StatLogic\Wrath_Logic.lua:3722
 RemoveEnchant = <function> defined @StatLogic\StatLogic.lua:2095
 GetBlockValuePerStr = <function> defined @StatLogic\StatLogic.lua:1635
 GetParryChanceBeforeDR = <function> defined @StatLogic\Wrath_Logic.lua:3648
 BuildGemmedTooltip = <function> defined @StatLogic\StatLogic.lua:2138
 GetAPFromAgi = <function> defined @StatLogic\StatLogic.lua:1755
 GetSpellCritFromInt = <function> defined @StatLogic\StatLogic.lua:2016
 GetDiff = <function> defined @StatLogic\StatLogic.lua:3011
 GetAPPerAgi = <function> defined @StatLogic\StatLogic.lua:1713
 StatModTable = <table> {
 }
 GetHealthRegenFromSpi = <function> defined @StatLogic\StatLogic.lua:2075
 GetEffectFromRating = <function> defined @StatLogic\StatLogic.lua:1510
 StatTable = <table> {
 }
 GetNormalManaRegenFromSpi = <function> defined @StatLogic\Wrath_Logic.lua:167
 GetBlockValueFromStr = <function> defined @StatLogic\StatLogic.lua:1674
 PatternTest = <function> defined @StatLogic\StatLogic.lua:3127
 Bench = <function> defined @StatLogic\StatLogic.lua:3107
 GenericStatMap = <table> {
 }
 GetGemID = <function> defined @StatLogic\StatLogic.lua:2228
 GetAPPerStr = <function> defined @StatLogic\StatLogic.lua:1556
 GetDodgePerAgi = <function> defined @StatLogic\StatLogic.lua:1901
 tipMiner = StatLogicMinerTooltip {
 }
 GetEffectFromDefense = <function> defined @StatLogic\StatLogic.lua:1448
 GetMissedChanceBeforeDR = <function> defined @StatLogic\Wrath_Logic.lua:3572
 RemoveGem = <function> defined @StatLogic\StatLogic.lua:2099
 GetOrderedTalentInfo = <function> defined @StatLogic\StatLogic.lua:1343
 GetAPFromStr = <function> defined @StatLogic\StatLogic.lua:1592
 RatingExists = <function> defined @StatLogic\StatLogic.lua:1461
 GetDodgeFromAgi = <function> defined @StatLogic\StatLogic.lua:1931
 GetCritFromAgi = <function> defined @StatLogic\StatLogic.lua:1967
 GetBaseDodge = <function> defined @StatLogic\StatLogic.lua:1869
 GetDiffID = <function> defined @StatLogic\StatLogic.lua:2878
}
avoidanceType = "MELEE_HIT_AVOID"
avoidanceBeforeDR = 0
class = 11
C = <table> {
 1 = 16
 2 = 16
 3 = 16
 4 = 16
 5 = 16
 6 = 16
 7 = 16
 8 = 16
 9 = 16
 10 = 16
}
(*temporary) = nil
(*temporary) = "DRUID"
(*temporary) = 11
(*temporary) = "nil"
(*temporary) = "string"
(*temporary) = "number"
(*temporary) = "attempt to perform arithmetic on field '?' (a nil value)"
StatLogic = <table> {
 GetRAPFromAgi = <function> defined @StatLogic\StatLogic.lua:1832
 GetReductionFromA

### Addon Source

GitHub Releases

### Version

1.5.8

### Locale

English

### Talent Specialization

Feral Druid

### Race

Night Elf

**Comment by raethkcj** [comment]
Hi, version 1.5.14 is the latest version, and I believe this was fixed already. Make sure to update, thanks!
