### ISSUE TITLE
[Bug]: Fury Warrior weapon stats missing

### ISSUE THREAD

**Issue by JB-90** [raethkcj/RatingBuster#110]
### Describe the bug

I'm not sure if it's a bug or just a wrong setting.

I am wearing 2 2-handed weapons as fury, but when I am hovering over a 2-handed weapon in my inventory, i can only see values of my mainhand or probably a summed up version of both hands(mainhand values seem to be incorrect, so I assume both hands get summed up)

When using 2 1-handed weapons, everything is fine.

### Addon Source

WowUp

### Version

1.5.15

### Locale

German

### Talent Specialization

Fury Warrior

### Race

Draenei

**Comment by raethkcj** [comment]
Thank you for reporting!
