### ISSUE TITLE
[Bug]: Items with armor pen stat summary missing

### ISSUE THREAD

**Issue by JB-90** [raethkcj/RatingBuster#111]
### Describe the bug

When I hover over an item with armor penetration, I don't get the sigma valueoverview(directly translated from german client).

I tried it with different items in my bags and with AtlasLoot but never get a list with values when arp is present. All other items seem to work.

### Addon Source

WowUp

### Version

1.5.16

### Locale

German

### Talent Specialization

Fury Warrior

### Race

Draenei

**Comment by raethkcj** [comment]
Thank you, should be fixed.
