### ISSUE TITLE
[Bug]: Stat breakdown on Jewelcrafting gem designs shown twice

### ISSUE THREAD

**Issue by the-chuppa** [raethkcj/RatingBuster#114]
### Describe the bug

Stat breakdown on Jewelcrafting gem designs is added twice and (most likely due to this bug) the text color is not properly changed back.

The item level and id is also added twice to the tooltip.

![image](https://user-images.githubusercontent.com/71234359/198113910-d575a636-9fa6-43a8-9098-df83e97d9194.png)

### Addon Source

GitHub Releases

### Version

1.5.17

### Locale

English

### Talent Specialization

Blood Death Knight

### Race

Dwarf

**Comment by raethkcj** [comment]
Thank you! Should be fixed.
