### ISSUE TITLE
Error in 1.6.0 with wotlk

### ISSUE THREAD

**Issue by Knakriktsur** [raethkcj/RatingBuster#115]
WOTLK
RB 1.6.0
Ger Client

419x StatLogic\locales\deDE-Deutsch.lua:10: bad argument #1 to 'gsub' (string expected, got nil)
[string "=[C]"]: in function `gsub'
[string "@StatLogic\locales\deDE-Deutsch.lua"]:10: in function <StatLogic\locales\deDE.lua:5>
[string "@StatLogic\StatLogic-78899.lua"]:2583: in function `GetSum'
[string "@RatingBuster\RatingBuster-1.6.0.nil.lua"]:3427: in function `StatSummary'
[string "@RatingBuster\RatingBuster-1.6.0.nil.lua"]:1718: in function `handler'
[string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: in function `OnTooltipSetItem'
[string "@Enchantrix\EnxMain.lua"]:232: in function <Enchantrix\EnxMain.lua:228>
[string "=[C]"]: in function `SetCompareItem'
[string "@FrameXML\GameTooltip.lua"]:652: in function <FrameXML\GameTooltip.lua:649>
[string "=[C]"]: in function `GameTooltip_ShowCompareItem'
[string "@!MoncaiCompare\!MoncaiCompare-7.2.0.lua"]:48: in function <!MoncaiCompare\!MoncaiCompare.lua:46>
...
[string "@Enchantrix\EnxMain.lua"]:232: in function <Enchantrix\EnxMain.lua:228>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua"]:434: in function <Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428>
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:107: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML\ContainerFrame_Shared.lua"]:1333: in function `ContainerFrameItemButton_OnEnter'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:349: in function `UpdateTooltip'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:184: in function <...faceBagnon\common\Wildpants\classes\item.lua:179>

Locals:
(*temporary) = nil
(*temporary) = ","
(*temporary) = "%."
(*temporary) = "string expected, got nil"

**Comment by raethkcj** [comment]
Fixed, thanks. Sorry about that!

**Comment by Knakriktsur** [comment]
No problem, thank you :)
