### ISSUE TITLE
[Bug]: Occasional tooltip duplication issue

### ISSUE THREAD

**Issue by boktai1000** [raethkcj/RatingBuster#116]
### Describe the bug

![image](https://user-images.githubusercontent.com/9054563/199616334-dc4f9cf6-78cf-400d-8902-6b6d7de9bb96.png)

### Addon Source

GitHub Releases

### Version

1.5.17

### Locale

English

### Talent Specialization

Frost Death Knight

### Race

Gnome

**Comment by raethkcj** [comment]
Can you check with version 1.6.1? This *should* be fixed, although these nested recipe things are really finnicky. It's technically the opposite side of the issue in #80 and is sort of a balancing act to prevent both happening on all items.

**Comment by boktai1000** [comment]
Here's using 1.6.1

![image](https://user-images.githubusercontent.com/9054563/199839682-57723270-a7cb-4656-a5af-618cba0ea695.png)


It is strange though, because I re-tested it on 1.5.17 and it looked fine when I checked it again another time. It is hard for me to reproduce and say for sure. Maybe you can close this if you feel like it's resolved and if I happen to see it again, I can re-open the issue or open a new issue. Thanks for looking into it!

**Comment by raethkcj** [comment]
Since there was a fix in 1.6.0 specifically for a Jewelcrafting recipe, I will close this for now. I checked as big a variety of recipes as I could, and didn't see any problems, but it's always possible some have slipped through the cracks.
