### ISSUE TITLE
[Bug]: Molten Armor and Molten Armor Glyph Spirit conversion into crit

### ISSUE THREAD

**Issue by Ulfenghard** [raethkcj/RatingBuster#123]
### Describe the bug

The Molten Armor spell and the glyph for it don't give the % of crit rating next to SPIRIT stat, so it's hard to compare items with or without spirit as a fire mage

### Addon Source

Curseforge

### Version

3.4.0.31

### Locale

English

### Talent Specialization

Fire Mage

### Race

Human

**Comment by raethkcj** [comment]
Hi, this is working properly in this version of the addon. If you installed from Curseforge then you are using https://github.com/CKNOEP/RatingBuster

**Comment by Ulfenghard** [comment]
You're right man, i'm so sorry for the mistake and making you lose time. Any chance to auto update addon? Or do i have to check here and download it again in case? Thank you very much

**Comment by raethkcj** [comment]
No problem at all, I'd much rather have an extra report than have an issue fly under the radar. I publish this version of the addon several places that have addon updaters, linked here: https://github.com/raethkcj/RatingBuster#installation
