### ISSUE TITLE
[Bug]: Resiliance breakdown bug in RU locale and items to exclude

### ISSUE THREAD

**Issue by Mard35** [raethkcj/RatingBuster#126]
### Describe the bug

1) For some reason Detailed text for Resiliance is not working at all in russian locale

![resilence-bug](https://user-images.githubusercontent.com/61734903/202333879-b8eb955f-4ad5-4d48-a821-101be2f54b59.jpg)

2) Austere Earthsiege Diamond 2% armor part should be excluded from scanning. 
It converts 2 armor, not 2 percent to attack power bacuse of Bladed Armor / Armored to the Teeth talents. For some reason it's only doing it on gear, but not on separate gem.

![Austere Earthsiege Diamond-bug](https://user-images.githubusercontent.com/61734903/202333919-6c842749-b0f1-4de4-b931-e82d8e53bbd1.jpg)

3) Annihilator should be excluded from scanning. Target armor should not be converted.

![Annihilator-exclude](https://user-images.githubusercontent.com/61734903/202333985-7d609727-25ae-489b-b4a6-3a48bc574364.jpg)

### Addon Source

GitHub Releases

### Version

1.6.4

### Locale

Russian

### Talent Specialization

Arms Warrior

### Race

Undead

**Comment by raethkcj** [comment]
Thanks, I believe these should all be fixed as of version 1.6.5.
