### ISSUE TITLE
frFR small update

### ISSUE THREAD

**Issue by Evorage** [raethkcj/RatingBuster#129]
Hi,

https://www.wowhead.com/wotlk/item=44664/favor-of-the-dragon-queen

Armor penetration wasn't working about this item both in sum stat and on the "score" line, because the french phrasing was slightly different vs other items.
I've updated both frFR files in StatLogic and RB.

adding this at line 460 for StatLogic :
`["la pénétration d'armure"] = {"ARMOR_PENETRATION_RATING"},`

and this at line 608 for RB :
`{pattern = "pénétration d'armure", id = CR_ARMOR_PENETRATION},`

Sorry, I don't know at all how to make a "pull request"

Thanks

**Comment by raethkcj** [comment]
Fixed in #131, #132, thank you!
