### ISSUE TITLE
[Bug]: Wrath Classic - Incorrect conversion Intelect to RAP for Hunter's - Talent Careful Aim

### ISSUE THREAD

**Issue by Andreatti** [raethkcj/RatingBuster#134]
### Describe the bug

The talent Careful Aim for MM Hunters gives 100% of the intelect converted to RAP (with 3 points).
Even with 3 points on the talent, the conversion is stoping at 1 point.

Ex: 66 Intelect > 22 RAP

![image](https://user-images.githubusercontent.com/9450279/210279309-cbc9fad8-4f3a-4e6e-9721-e898728c3a25.png)

In this image we can see RAP total is wrong, 375 its not the correct value.

### Addon Source

Curseforge

### Version

3.4.0 (from 02/01/2023)

### Locale

English

### Talent Specialization

Marksmanship Hunter

### Race

Orc

**Comment by raethkcj** [comment]
Hello, I don't publish this version of the addon on Curseforge. You are likely using https://github.com/CKNOEP/RatingBuster.

Careful Aim appears to be working in my version of the addon.

Sorry for the confusion.
