### ISSUE TITLE
[Bug]: attempt to index upvalue 'globalDB' (a nil value), NonEmptySpell:ContinueOnLoad(callbackFunction)

### ISSUE THREAD

**Issue by Sakatard** [raethkcj/RatingBuster#135]
### Describe the bug

upon login on my warlock I get:

4x Interface\AddOns\RatingBuster\RatingBuster-(development).nil.lua:1454: Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)
[string "=[C]"]: in function `error'
[string "@Interface\FrameXML\ObjectAPI\Spell.lua"]:53: in function `ContinueOnSpellLoad'
[string "@Interface\AddOns\RatingBuster\RatingBuster-(development).nil.lua"]:1454: in function <Interface\AddOns\RatingBuster\RatingBuster.lua:1434>
[string "@Interface\AddOns\RatingBuster\RatingBuster-(development).nil.lua"]:1469: in function <Interface\AddOns\RatingBuster\RatingBuster.lua:1466>

Locals:
(*temporary) = "Usage: NonEmptySpell:ContinueOnLoad(callbackFunction)"

and

30x Interface\AddOns\RatingBuster\RatingBuster-(development).nil.lua:1655: attempt to index upvalue 'globalDB' (a nil value)
[string "@Interface\AddOns\RatingBuster\RatingBuster-(development).nil.lua"]:1655: in function `handler'
[string "@Interface\AddOns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetAction'
[string "@Interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0-70.lua"]:2440: in function `SetTooltip'
[string "@Interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0-70.lua"]:2141: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:2133>
[string "@Interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0-70.lua"]:1098: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1096>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `handler'
[string "@Interface\AddOns\CustomFlyout\Libs\LibFlyoutFrame\LibFlyoutFrame.lua"]:977: in function <...\CustomFlyout\Libs\LibFlyoutFrame\LibFlyoutFrame.lua:971>

Locals:
tooltip = GameTooltip {
 0 = <userdata>
 SetUnitBuff = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:191
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:195
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 default = 1
 SetCraftItem = <function> defined =[C]:-1
 __tooltipUpdated = true
 Hide = <function> defined =[C]:-1
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:199
 SetPetAction = <function> defined =[C]:-1
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 hasMoney = 1
 SetBorderBlendMode = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:203
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 2
 StatusBar = GameTooltipStatusBar {
 }
 SetInboxItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 shoppingTooltips = <table> {
 }
 SetRecipeResultItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:101
 SetTradeTargetItem = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:101
 SetTradePlayerItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:101
 SetSendMailItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 updateTooltip = 0.050000
 SetInventoryItem = <function> defined =[C]:-1
 qualityChanged = true
 NineSlice = <unnamed> {
 }
 TooltipBackdropOnLoad = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:172
 SetUnitAura = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 SetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:187
 SetLootRollItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
name = ""
link = "|cffa335ee|Hitem:40750:3606:::::::80:::::::::|h[Xintor's Expeditionary Boots]|h|r"
itemType = 4
isRecipe = false
(*temporary) = nil
(*temporary) = "Armor"
(*temporary) = "Cloth"
(*temporary) = "INVTYPE_FEET"
(*temporary) = 132560
(*temporary) = 4
(*temporary) = 1
(*temporary) = 4
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'globalDB' (a nil value)"
select = <function> defined =[C]:-1
calcLevel = nil
globalDB = nil
playerLevel = 80
GetItemInfo = <function> defined @Interface\AddOns\RatingBuster\RatingBuster.lua:80
profileDB = nil
StatLogic = <table> {
 GetRAPFromAgi = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1901
 GetReductionFromArmor = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1490
 GetSum = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:2393
 argCheck = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:77
 GetDodgeChanceBeforeDR = <function> defined @Interface\AddOns\StatLogic\Wrath_Logic.lua:3833
 GetRAPPerAgi = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1862
 GetStatMod = <function> defined @Interface\AddOns\StatLogic\StatLogic.lua:1456
 Ta

### Addon Source

GitHub Releases

### Version

84128389875a818a4dbc66ff8e51b89f5a6a4114

### Locale

English

### Talent Specialization

Demonology Warlock

### Race

Gnome

**Comment by raethkcj** [comment]
Thanks for the report! Seems to have been a minor issue with Demonic Pact. Should be fixed in 1.7.2.
