### ISSUE TITLE
[Bug]: Feral armor incorrectly reported on rings (and probably necks, cloaks, and trinkets)

### ISSUE THREAD

**Issue by merijn** [raethkcj/RatingBuster#136]
### Describe the bug

The stat summary shows a ring with 308 armor giving 1900ish armor. However, as of wrath bear form/dire bear form only affects armor from cloth and leather items (and also does not affect bonus, i.e. green armor). The armor on rings/necks/cloaks/trinkets should there for not be modified by the bear form modifier.

### Addon Source

Curseforge

### Version

1.7.2

### Locale

English

### Talent Specialization

Feral Druid

### Race

Night Elf

**Comment by raethkcj** [comment]
Should be fixed in 1.7.3.

Side note, if you installed from Curseforge, you're probably using https://github.com/CKNOEP/RatingBuster instead of this version. I distribute this version in these places: https://github.com/raethkcj/RatingBuster#installation
