### ISSUE TITLE
[Bug]: Mouseover item causes text output to chat

### ISSUE THREAD

**Issue by Phatlynx** [raethkcj/RatingBuster#137]
### Describe the bug

Mousing over any item from Character panel causes RatingBuster to output PreScan/DeepScan2 messages to chat. 
![image](https://user-images.githubusercontent.com/67671220/213214591-60b87691-da1f-4175-998b-a5d27028096f.png)

### Addon Source

WoWInterface

### Version

3.4.1.00

### Locale

English

### Talent Specialization

Affliction Warlock

### Race

Undead

**Comment by raethkcj** [comment]
This is odd, did you somehow use the slash command `/sldebug` (**S**tat**L**ogic Debug)? Does using the command again turn it off?

**Comment by raethkcj** [comment]
It looks like you may have actually installed https://github.com/CKNOEP/RatingBuster instead of this version. I'm seeing numerous reports of the same issue there. I wasn't aware CKNOEP published on WoWInterface, though.
