### ISSUE TITLE
[Locale fix] Missing line for spellpower to french locale in StatLogic

### ISSUE THREAD

**Issue by Hantunaar** [raethkcj/RatingBuster#144]
Hi
I can't find StatLogic  anymore on github so I'm bringing up the issue here; spellpower isn't recognized with WotLK wording and it can be fixed by adding :
["la puissance des sorts"] = {"SPELL_DMG", "HEAL",},
at line 319 or so, within StatLogic\locale\frFR.lua

So yeah, can you please fix that, and is StatLogic still around on here and am i being dumb for not seeing it?
Thank you and have a good day

**Comment by raethkcj** [comment]
Thanks, added! And StatLogic is still located here: https://github.com/raethkcj/RatingBuster/tree/master/libs/StatLogic
