### ISSUE TITLE
Classic Era - Error on Quest Item Window

### ISSUE THREAD

**Issue by Jorvanus** [raethkcj/RatingBuster#150]
Happens when I have a quest window open with items as rewards.  

361x Interface\AddOns\RatingBuster\RatingBuster-1.7.10.nil.lua:1728: attempt to index a nil value
[string "@Interface\AddOns\RatingBuster\RatingBuster-1.7.10.nil.lua"]:1728: in function `handler'
[string "@Interface\AddOns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCompareItem'
[string "@Interface\FrameXML\GameTooltip.lua"]:650: in function <Interface\FrameXML\GameTooltip.lua:647>
[string "=[C]"]: in function `GameTooltip_ShowCompareItem'
[string "@Interface_Vanilla\FrameXML\QuestInfo.lua"]:998: in function <Interface_Vanilla\FrameXML\QuestInfo.lua:986>

Locals:
tooltip = ShoppingTooltip1 {
 0 = <userdata>
 SetText = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:191
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:195
 SetCraftItem = <function> defined =[C]:-1
 ClearLines = <function> defined =[C]:-1
 ARKTTD = <table> {
 }
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:199
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:203
 FadeOut = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 PawnIconFrame = <unnamed> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 SetCompareItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 updateTooltip = 0.200000
 NineSlice = <unnamed> {
 }
 SetInventoryItem = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 TooltipBackdropOnLoad = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:172
 layoutType = "TooltipDefaultLayout"
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetCraftSpell = <function> defined =[C]:-1
 SetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:187
 BottomOverlay = <unnamed> {
 }
 SetAuctionItem = <function> defined =[C]:-1
}
name = "Worn Mace"
link = "|cffffffff|Hitem:36::::::::4:::::::::|h[Worn Mace]|h|r"
(*temporary) = <table> {
 WorldFrame = true
 UIParent = true
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"
scanningParents = <table> {
 WorldFrame = true
 UIParent = true
}
select = <function> defined =[C]:-1
calcLevel = 4
globalDB = <table> {
 sumShowIcon = true
 calcDiff = true
 sumIgnoreEquipped = false
 hideBlizzardComparisons = true
 sumBlankLineAfter = false
 sumShowTitle = true
 showItemLevel = false
 showSum = true
 sumStatColor = <table> {
 }
 calcSum = true
 showItemID = false
 sumValueColor = <table> {
 }
 useRequiredLevel = true
 sumSortAlpha = false
 sumIgnoreUnused = true
 sumIgnoreEnchant = true
 sumBlankLine = true
 customLevel = 0
 sumDiffStyle = "main"
 sumIgnoreGems = false
 textColor = <table> {
 }
}
playerLevel = 4
GetItemInfo = <function> defined @Interface\AddOns\RatingBuster\RatingBuster.lua:79
profileDB = <table> {
 sumFireResist = false
 sumNatureDmg = false
 sumHitAvoid = false
 sumTankPoints = false
 sumHaste = false
 sumGemBlue = <table> {
 }
 sumDodgeNeglect = false
 enableAvoidanceDiminishingReturns = false
 showRAPFromAgi = false
 sumCrit = false
 sumShadowResist = false
 sumFireDmg = false
 sumMP5NC = false
 sumBlockNeglect = false
 sumFrostResist = false
 sumShadowDmg = false
 sumRangedHit = false
 showStats = true
 sumGemYellow = <table> {
 }
 showArmorFromAgi = false
 sumSpellHit = true
 sumIgnoreArmor = false
 sumHealing = true
 showMP5FromSpi = true
 showBlockValueFromStr = false
 sumNatureResist = false
 sumHP5OC = false
 showSpellCritFromInt = true
 sumRangedCritRating = false
 sumSpi = false
 sumParryNeglect = false
 sumSpellHasteRating = false
 sumArcaneDmg = false
 sumAvoidWithBlock = false
 sumDefense = false
 sumSpellCritRating = false
 sumTotalReduction = fal

**Comment by raethkcj** [comment]
Thanks for the report! Do you still get an error in 1.7.11? It fixed a similar issue with vendors in Wrath.
