### ISSUE TITLE
[Bug]: Comparing items not showing HP and mana difference in result

### ISSUE THREAD

**Issue by Iowerth** [raethkcj/RatingBuster#152]
### Describe the bug

Hi. When compare 2 items then there is no showing HP and mana difference in result. It is enabled in settings.
PS: don't know how to show screenshot in English. Even tried to replace localization files ruRU to enUS in RatingBuster and in StatLogic.

![2023-05-25 00_00_51-Greenshot image editor](https://github.com/raethkcj/RatingBuster/assets/10152411/a2b3fd32-a42b-4e6a-8cbb-1b3d65d7406b)

### Addon Source

CurseForge

### Version

1.7.12

### Locale

Russian

### Talent Specialization

Fire Mage

### Race

Blood Elf

**Comment by raethkcj** [comment]
Thank you for reporting this! It was actually pretty tricky to track down the cause, but a pretty simple fix.

**Comment by Iowerth** [comment]
Thanks!
