### ISSUE TITLE
[Bug]: Tooltips don't work from 1.7.9 onwards

### ISSUE THREAD

**Issue by Vishiswaz** [raethkcj/RatingBuster#153]
### Describe the bug

I was using version 1.7.5 since it released, just remembered to update today. Upon installing 1.7.12 I noticed my tooltips were not showing any stat changes anymore.

After downloading a LOT of versions and doing installs and reloads (and firstly trying a fresh install and clearing cache and disabling all other addons) I found that the tooltips work in 1.7.8 but not in 1.7.9 or later. I'll use 1.7.8 until it's fixed.

My character is a level 41 draenei enhancement shaman. No, it's not just Mail armor, it's Leather too. What can I send you to help you debug this?

### Addon Source

GitHub Releases

### Version

1.7.8

### Locale

English

### Talent Specialization

Enhancement Shaman

### Race

Draenei

**Comment by raethkcj** [comment]
Do you still experience this with all addons besides RatingBuster and StatLogic disabled?

If yes, do you have Lua errors enabled? Preferably enable BugSack+BugGrabber, alternatively use `console scriptErrors 1`

If not, are you able to identify which addon(s) cause a conflict?

**Comment by Vishiswaz** [comment]
To be clear, my tooltips work. The Ratingbuster part of the tooltip is what doesn't work. I've tried it with all addons disabled except RB and SL. It's not an addon conflict.

I don't know what BugSack and BugGrabber are.

**Comment by raethkcj** [comment]
They are addons, and the easiest way to keep track of Lua errors. I also gave an alternative command to run if you don't want to install them.

**Comment by Vishiswaz** [comment]
Alright, I've installed the addons.

![image](https://github.com/raethkcj/RatingBuster/assets/78314117/b076a23f-f430-41cb-baec-c36abc658634)

**Comment by raethkcj** [comment]
Thank you, fixed in 1.7.13

**Comment by Vishiswaz** [comment]
Confirmed working. Thanks!
