### ISSUE TITLE
[Bug]: Green/Purple Stamina gems not recognized in french

### ISSUE THREAD

**Issue by Hantunaar** [raethkcj/RatingBuster#156]
### Describe the bug

Hi,

I just noticed that the wording on green and purple gems is different in French compared to everywhere else, and as a result, stamina isn't being counted. By adding the line:

["à l'Endurance"] = {StatLogic.Stats.Stamina},

at line 244 in frFR.lua from StatLogic\Locales, it fixes the issue :)

### Addon Source

CurseForge

### Version

1.10

### Locale

French

### Talent Specialization

Frost Death Knight

### Race

Blood Elf

**Comment by Hantunaar** [comment]
Actually it happens with every primary stat on the purple/green gems so here is the complete change, starting at line 239:

	["à toutes les caractéristiques"] = {StatLogic.Stats.Strength, StatLogic.Stats.Agility, StatLogic.Stats.Stamina, StatLogic.Stats.Intellect, StatLogic.Stats.Spirit},
	["Force"] = {StatLogic.Stats.Strength},
	["à la Force"] = {StatLogic.Stats.Strength},
	["Agilité"] = {StatLogic.Stats.Agility},
	["à l'Agilité"] = {StatLogic.Stats.Agility},
	["Endurance"] = {StatLogic.Stats.Stamina},
	["en endurance"] = {StatLogic.Stats.Stamina},
	["à l'Endurance"] = {StatLogic.Stats.Stamina},
	["Intelligence"] = {StatLogic.Stats.Intellect},
	["à l'Intelligence"] = {StatLogic.Stats.Intellect},
	["Esprit"] = {StatLogic.Stats.Spirit},
	["à l'Esprit"] = {StatLogic.Stats.Spirit},

**Comment by raethkcj** [comment]
Thank you for these!
