### ISSUE TITLE
How to fix position % values on stats crit, hit...

### ISSUE THREAD

**Issue by ZendorES** [raethkcj/RatingBuster#16]
I need to move the value in percentage to the end of stat 
![image](https://user-images.githubusercontent.com/85072858/120248889-3753c400-c279-11eb-8995-966e5ede6deb.png)

I need ."...X p. (x,xx%)"

Thx!!

**Comment by raethkcj** [comment]
Hmm, I made some changes that I *think* will work, although this could affect more than I'm intending, so I'd appreciate if you could test it:

https://github.com/raethkcj/RatingBuster/commit/14b56a630c5cda4e8d692cf45b82dd52a6deb3bf

**Comment by ZendorES** [comment]
Perfect!!! 
![image](https://user-images.githubusercontent.com/85072858/120368512-71bd6f80-c312-11eb-8c83-a53a4e9078e2.png)

Thx, I have many doubts, I am new to this and I need to make more changes, when I do not know how to continue I will tell you about it here!
