### ISSUE TITLE
[Bug]: BugSack dump after updating to RatingBuster 1.15.1

### ISSUE THREAD

**Issue by Mncdk** [raethkcj/RatingBuster#176]
### Describe the bug

Chilling in Redridge, questing on a Rogue when I get spammed with the "too many errors in your UI" message

I don't know if this is enough information for it to be useful to you at all.

431x StatLogic/Vanilla_Logic.lua:121: attempt to perform arithmetic on field '?' (a nil value)
[string "@StatLogic/Vanilla_Logic.lua"]:121: in function <StatLogic/Vanilla_Logic.lua:120>
[string "@StatLogic/StatLogic.lua"]:1345: in function `GetDodgePerAgi'
[string "@RatingBuster/RatingBuster.lua"]:2184: in function `ProcessStat'
[string "@RatingBuster/RatingBuster.lua"]:1935: in function <RatingBuster/RatingBuster.lua:1917>
[string "=(tail call)"]: ?
[string "@RatingBuster/RatingBuster.lua"]:1878: in function `ProcessLine'
[string "@RatingBuster/RatingBuster.lua"]:1820: in function <RatingBuster/RatingBuster.lua:1772>
[string "@RatingBuster/TipHooker.lua"]:8: in function <RatingBuster/TipHooker.lua:6>
[string "@RatingBuster/TipHooker.lua"]:30: in function <RatingBuster/TipHooker.lua:25>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCompareItem'
[string "@FrameXML/GameTooltip.lua"]:670: in function <FrameXML/GameTooltip.lua:662>
...
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML/ContainerFrame_Shared.lua"]:1425: in function <FrameXML/ContainerFrame_Shared.lua:1396>
[string "=[C]"]: in function `ContainerFrameItemButton_OnEnter'
[string "*ContainerFrame.xml:184_OnEnter"]:1: in function <[string "*ContainerFrame.xml:184_OnEnter"]:1>

Locals:
_ = <table> {
}
level = 18
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field '?' (a nil value)"
addon = <table> {
 CritPerAgi = <table> {
 }
 class = "ROGUE"
 StatModValidators = <table> {
 }
 BuffGroup = <table> {
 }
 playerRace = "Dwarf"
 zero = <table> {
 }
 SpellCritPerInt = <table> {
 }
 DodgePerAgi = <table> {
 }
 StatModCacheInvalidators = <table> {
 }
}

### Addon Source

WowUp

### Version

1.15.1

### Locale

English

### Talent Specialization

Combat Rogue

### Race

Dwarf

**Comment by raethkcj** [comment]
Thanks for the report, fix should be released shortly!
