### ISSUE TITLE
[Bug]: settings reset

### ISSUE THREAD

**Issue by Toodo** [raethkcj/RatingBuster#179]
### Describe the bug

Hello
my stat breakdown reset everytime i logout from my chare
need to go on addons go to agility and check attack power eveytime

### Addon Source

CurseForge

### Version

4.4.0 cata

### Locale

English

### Talent Specialization

Assassination Rogue

### Race

Human

**Comment by raethkcj** [comment]
Hello, thanks for the report. The latest version of this addon on Curseforge is 1.15.4, can you confirm you're using that version?

https://www.curseforge.com/wow/addons/ratingbuster-classic

**Comment by Toodo** [comment]
im sorry im using someone else addon with the same name im gonna change to yours might works better :D
