### ISSUE TITLE
[Feature Request] Ignore Armor Types

### ISSUE THREAD

**Issue by nistra123** [raethkcj/RatingBuster#180]
Give option to Ignore Armor Types

like when youre an resto shaman

ignore leather
ignore cloth cuz of the 5% mail int buff
and if possible also ignore agility items (for ele/resto or ignore intellect for enhance)
would be absolutly awesome,ty

**Comment by raethkcj** [comment]
Thanks for the suggestion. A setting to ignore based on Armor Types already exists, but apparently isn't functioning due to a change in Cata Classic, so I'll fix that first and also look into a separate setting for primary stats.
