### ISSUE TITLE
[Bug]: Digit grouping in tooltips breaks conversion of stats

### ISSUE THREAD

**Issue by lordblackadder** [raethkcj/RatingBuster#181]
### Describe the bug

Latest Cata patch seems to have introduced digit grouping in values of tooltips, separating thousands. This messes up the conversion to percentages/stats because it's converting the values before the comma.
![image](https://github.com/raethkcj/RatingBuster/assets/12127284/a63b13f5-154a-4af4-a5c7-3712d2c9b827)
![image](https://github.com/raethkcj/RatingBuster/assets/12127284/d42f2270-0bb3-4c8c-acbf-7d62b19cccce)
![image](https://github.com/raethkcj/RatingBuster/assets/12127284/5a381c9e-bb56-464d-8d84-51b118bb24a5)

### Addon Source

CurseForge

### Version

1.16.8

### Locale

English

### Talent Specialization

Blood Death Knight

### Race

Draenei

**Comment by vertx66** [comment]
Confirming this bug too 
![image](https://github.com/raethkcj/RatingBuster/assets/75558294/d03f5f64-e354-41cd-8732-e8c0b385f1da)

**Comment by raethkcj** [comment]
Thanks for the report, should be fixed in 1.16.9! Also fixed that very long AP string for items that *actually* have 1 armor.
