### ISSUE TITLE
[Bug]: Localization entry missing

### ISSUE THREAD

**Issue by Road-block** [raethkcj/RatingBuster#186]
### Describe the bug

```lua
1x AceLocale-3.0-6: RatingBuster: Missing entry for 'StatSummary'
```

### Addon Source

CurseForge

### Version

1.18.0

### Locale

English

### Talent Specialization

Protection Warrior

### Race

Human

**Comment by Road-block** [comment]
Ok the problem is in-fact at L:3600 of RatingBuster.lua
L["StatSummary"] instead of L["Stat Summary"] which is the entry found in the localization table.

**Comment by raethkcj** [comment]
Huh, embarrassing copy paste error, thanks!
