### ISSUE TITLE
[Feature Request] (SOD) AlwaysBuffed Spirit of Zandalar

### ISSUE THREAD

**Issue by TormDeltest** [raethkcj/RatingBuster#188]
Hello, 

Can you add Spirit of Zandalar as AlwaysBuffed option into the addon? Adds flat 15% to all stats similar to the Fervor of the Temple Explorer (used to give 8%). 

Would be very helpful.

Thank you!

**Comment by raethkcj** [comment]
Thanks for the suggestion, I had missed it!
