### ISSUE TITLE
[Bug]: LUA Error when in game

### ISSUE THREAD

**Issue by Aenimma** [raethkcj/RatingBuster#189]
### Describe the bug

Date: 2024-10-31 19:48:21
ID: -1
Error occured in: Global
Count: 1
Message: Interface/AddOns/RatingBuster/RatingBuster.lua line 1815:
   attempt to call method 'GetDiffID' (a nil value)
Debug:
   [string "=[C]"]: GetDiffID()
   [string "@Interface/AddOns/RatingBuster/RatingBuster.lua"]:1815:
      Interface/AddOns/RatingBuster/RatingBuster.lua:1794
   [string "@Interface/AddOns/RatingBuster/TipHooker.lua"]:8:
      Interface/AddOns/RatingBuster/TipHooker.lua:6
   [string "@Interface/AddOns/RatingBuster/TipHooker.lua"]:16:
      Interface/AddOns/RatingBuster/TipHooker.lua:14
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
Locals:

### Addon Source

CurseForge

### Version

1.19.0

### Locale

English

### Talent Specialization

Unholy Death Knight

### Race

Orc

**Comment by raethkcj** [comment]
Hmm, based on the error, it sounds like a separate error may be preventing StatLogic from loading. Are there any earlier (further to the left in BugSack) errors related to StatLogic?

**Comment by Aenimma** [comment]
Hello yes there is

Date: 2024-10-31 23:34:58
ID: -7
Error occured in: Global
Count: 1
Message: Interface/AddOns/StatLogic/StatLogic.lua line 1734:
   attempt to index global 'GREENCOLORCODE' (a nil value)
Debug:
   [string "@Interface/AddOns/StatLogic/StatLogic.lua"]:1734: in main chunk
Locals:
addonName = "StatLogic"
addon = <table> {
 PreScanPatterns = <table> {
 }
 PrefixExcludeLength = 5
 StatIDLookup = <table> {
 }
 WholeTextLookup = <table> {
 }
 PrefixExclude = <table> {
 }
 BuffGroup = <table> {
 }
 zero = <table> {
 }
 playerRace = "Scourge"
 class = "MAGE"
 StatModValidators = <table> {
 }
 WeaponRacials = <table> {
 }
 StatModCacheInvalidators = <table> {
 }
}
StatLogic = <table> {
 Stats = <table> {
 }
 StatTable = <table> {
 }
 ExtraHasteClasses = <table> {
 }
 GenericStatMap = <table> {
 }
 StatModInfo = <table> {
 }
 StatModIgnoresAlwaysBuffed = <table> {
 }
}
tip = StatLogicTooltip {
 NineSlice = Frame {
 }
 layoutType = "TooltipDefaultLayout"
 updateTooltip = 0.200000
 TopOverlay = Texture {
 }
 needsReset = true
 BottomOverlay = Texture {
 }
 sides = <table> {
 }
}
_G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 SettingsSliderOptionsMixin = <table> {
 }
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 UNIT_NAMEPLATES_TYPE_TOOLTIP_3 = "This method avoids overlapping nameplates by spreading them out horizontally and vertically."
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 798
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 413
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this group."
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Toggles an additional optional actionbar on the right side of the screen."
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 365
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 ERR_NOAMMO_S = "%s"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 PlayerTalentFramePanel3Talent25 = PlayerTalentFramePanel3Talent25 {
 }
 CONSOLIDATED_BUFFS_PER_ROW = 4
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 33
 INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
 SLASH_LibQTip1 = "/qtip"
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 GRM_BirthdayTooltipStatusBar = GRM_BirthdayTooltipStatusBar {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 VOICEMACRO_4_Sc_1_FEMALE = "Help me attack!"
 StanceButton4FlyoutArrow = StanceButton4FlyoutArrow {
 }
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 AUCTIONATOR_L_DEFAULT_LIST_HEADER = "Default Shopping List"
 DMG_LCD = "DMG"
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 SLASH_STOPATTACK1 = "/stopattack"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle {
 }
 ContainerFrame4Item16Cooldown = ContainerFrame4Item16Cooldown {
 }
 MINIMAP_TRACKING_TRAINER_CLASS = "Class Trainer"
 SLASH_DISMOUNT2 = "/dismount"
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 GRM_PlayerListOfAlts_Save = <table> {
 }
 EMOTE69_CMD1 = "/nosepick"
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 SPELL_FAILED_CUSTOM_ERROR_152 = "You must choose a specialization to use Ascendance."
 AutoFollowStatus = AutoFollowStatus {
 }
 GuildControlPopupFrame = GuildControlPop

**Comment by raethkcj** [comment]
I think your addon updater may have had an issue, as `GREENCOLORCODE` should have been removed several versions ago. Can you try manually deleting the `RatingBuster` and `StatLogic` folders from `_wow_classic_/Interface/AddOns` and then reinstalling the latest version?

**Comment by raethkcj** [comment]
I did some digging, and based on the line numbers, it looks like you have either version 1.16.4 or 1.16.5 installed, which are from April! So yeah something got stuck in your addon updater, and the latest version of the addon shouldn't have these errors.

**Comment by Aenimma** [comment]
Hello, I deleted the addon and deleted RatingBuster and Statlogic Folders and re-downloaded the addon with the same error.

Date: 2024-11-02 15:24:02
ID: -17
Error occured in: Global
Count: 1
Message: Interface/AddOns/StatLogic/StatLogic.lua line 1734:
   attempt to index global 'GREENCOLORCODE' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/StatLogic/StatLogic.lua"]:1734: in main chunk
Locals:

**Comment by Aenimma** [comment]
Looks like it was another addon causing the issue TacoTip. This is now working.
