### ISSUE TITLE
Echants that add stats aren't included in the summary.

### ISSUE THREAD

**Issue by ClockworkGod** [raethkcj/RatingBuster#19]

**Comment by raethkcj** [comment]
Stat enchants seem to be working for me. Can you confirm whether you have this option checked? 

![image](https://user-images.githubusercontent.com/7716908/120714346-b3702680-c488-11eb-922f-7ac9427e4c4a.png)

**Comment by ClockworkGod** [comment]
well i feel like an idiot now, i didn't even think it would be ignored by default.
