### ISSUE TITLE
Working under BCC

### ISSUE THREAD

**Issue by RaggokPatchwork** [raethkcj/RatingBuster#2]
Dear raethkcj,

thank you so much for working on ratingbuster! I loved this addon in the older days (or was it a similar addon, I don`t remember).
Unfortunatly, I`m not able to get it working in BCC (loaded the correct version). There is no breakdown / there are no stats shown in the tooltip. I`m able to open the config with /rb, but e.g. /rb toggle as well as the other commands is not working. I just tried to run RB without any other addon to make sure there is nothing blocking it, same issue. Any ideas how to get it working? Do I need a special additional addon?

Best regards from Aachen, Germany
Raggok

**Comment by raethkcj** [comment]
Thanks for the report, I had forgotten to reformat all the non-english locale files. Should be fixed now.

**Comment by RaggokPatchwork** [comment]
Now it`s working perfect with the german client! Many thanks!!! :-)
