### ISSUE TITLE
v1.0.7 Release

### ISSUE THREAD

**Issue by 65zambo65** [raethkcj/RatingBuster#22]
Well for some reason the one marked as "RatingBuster-v1.0.7-bcc.zip", doesn't work with BCC at all. 
Funnily enough "RatingBuster-v1.0.7-classic.zip" seems to work fine even though its marked as classic and not bcc.

**Comment by raethkcj** [comment]
Any way you can elaborate? I installed the bcc version in a clean game install and it works fine.

**Comment by 65zambo65** [comment]
Well as I said the classic version works in bcc for me.
