### ISSUE TITLE
Summary overview - crit comparison is wrong

### ISSUE THREAD

**Issue by Neran28** [raethkcj/RatingBuster#26]
In the sum overview the comparison of crit% is wrong (german  client).
At least thats the case in the example of having two items of which the one item has crit% from an agility source and the other item has crit from crit rating source.
In this example the equipped item has 1.01% crit from crit rating while the item in the inventory does have 1.27% crit from agility. 
The comparison states that the item in the inventory results in a gain of 1.27% of crit% which means that the equipped item with the crit rating source is not taken into account. 

This bug is probably related to another bug that causes crit rating not being displayed or recognized at all in the summary, also when turned on in the settings.

**Comment by raethkcj** [comment]
It was likely a missing German translation, should be fixed.
