### ISSUE TITLE
Doesnt add all stats from Naxx shoulder enchants

### ISSUE THREAD

**Issue by HelveteTV** [raethkcj/RatingBuster#27]
![image](https://user-images.githubusercontent.com/52008308/121198227-438be280-c872-11eb-9860-cd4b9cde87e4.png)

Attack power in this case

**Comment by HelveteTV** [comment]
Same with ZG enchant
![image](https://user-images.githubusercontent.com/52008308/121208698-8ce03000-c87a-11eb-9f40-73c474ca3c26.png)

**Comment by raethkcj** [comment]
Do you have Stat Summary -> Ignore settings -> Ignore enchants checked? It's enabled by default.

**Comment by HelveteTV** [comment]
yea thats it, my bad, closing
