### ISSUE TITLE
Request - Support for WowUp

### ISSUE THREAD

**Issue by jodysaliba** [raethkcj/RatingBuster#3]
Currently, this doesn't show upon a search in [WowUp](https://wowup.io/). From their Discord, it looks like the authors need to let them know about their addon in order to be searchable. If you could do that, it'd be much appreciated.

**Comment by raethkcj** [comment]
I let them know, it sounds like it should be available either now or upon the next WoWUp update.

**Comment by jodysaliba** [comment]
Looks like it's there now! Thank you.
![image](https://user-images.githubusercontent.com/1418509/119563552-af038980-bd75-11eb-802b-8efc6a6319d6.png)

**Comment by kunambi** [comment]
Sorry for necro, but the addon version listed in wowup doesn't work. After downloading it from Githubs release page and /reloadui the `/rb` command works.

Perhaps should move to another thread?
