### ISSUE TITLE
Spirit -> MP5

### ISSUE THREAD

**Issue by zak-lambert** [raethkcj/RatingBuster#36]
The formula for Druids seems incorrect. The following formula should be correct for druids and I believe priests.

SpiritIntellectRegen = 5 * 0.00932715221261 * sqrt(Intellect) * Spirit
With intellect being the characters total int.

Not sure if you already pull totals though.

Also, intensity is 30% mp5 while casting, not 15%.

**Comment by raethkcj** [comment]
Looks like the regen formulas were all correct, there was just an error in the logic checking the game version.
