### ISSUE TITLE
Hit Chance not visible in Stat Summary, if game is running German

### ISSUE THREAD

**Issue by daniel-w-f** [raethkcj/RatingBuster#38]
In the tooltip stat summary the complete line for "Hit Chance(%)" is not visible at all if the game client is set to German. If the game is set to English and RatingBuster is using the same settings it is visible.

English working:
![grafik](https://user-images.githubusercontent.com/52549054/124661108-5dd3d300-dea7-11eb-85e8-201c76174856.png)

German not working
![grafik](https://user-images.githubusercontent.com/52549054/124661069-514f7a80-dea7-11eb-9a71-eff2bf2b3c9b.png)

**Comment by Mackiavelly** [comment]
in RU localization is so dont work
