### ISSUE TITLE
Agility Attack Power not showing nor calculating in totals

### ISSUE THREAD

**Issue by chefBrian** [raethkcj/RatingBuster#42]
Enhancement Shaman, en_US

If you look at this screenshot (below), you can see in my settings I have AP for agility enabled, however it is not showing on the tooltip.
![s1](https://user-images.githubusercontent.com/24285689/125558473-8c4b7ae1-2339-4f2b-a771-a4a4a5b4e6f5.png)

I believe this is also causing an issue in this second screen shot not calculating agility into the attack power sum for an item.  (I put the correct values and calculations in the screenshot.)
![s2](https://user-images.githubusercontent.com/24285689/125558483-209bc99d-8717-4df9-a17a-25b36c020f78.jpg)

**Comment by raethkcj** [comment]
Well, this is awkward. 

Thanks for your great write-up, but Enhancement Shamans don't actually get any AP from Agility in TBC. That didn't get changed until Cata.

**Comment by chefBrian** [comment]
Well this is awkward haha. After looking it up, you are correct. Sorry for the post!
