### ISSUE TITLE
Strength Tooltip Conversion (Shaman)

### ISSUE THREAD

**Issue by boktai1000** [raethkcj/RatingBuster#49]
When I was on my Shaman, I noticed this conversion listed for my Enh Shaman (70 Draenei Shaman - BC Classic)

![image](https://user-images.githubusercontent.com/9054563/132102414-d8a36dfc-c3a6-41cf-8020-8d565e4e1df0.png)

Now unless I'm crazy, 26 strength converting to "+16 dmg, +16 healing" doesn't quite seem right here.

**Comment by raethkcj** [comment]
You have the Mental Quickness talent?

26 str = 52 AP = ~16-17 spell power. 16 is probably accounting for some rounding method, since Blizzard often applies talents strangely.

**Comment by boktai1000** [comment]
![image](https://user-images.githubusercontent.com/9054563/132103724-92f6d39c-306a-4c52-822e-111c1116532b.png)

Ah I do, but I guess it wasn't very obvious! Shaman is my Alt so I thought - huh, this is very strange! Although when I see "Dmg" listed as well, I think similar to the enchants / stats that have a base flat damage increase - as it sort of implied melee instead of Spell Dmg. Usually Spell Hit, Spell Dmg, Spell Crit, etc are prefixed with Spell.
