### ISSUE TITLE
Error when hovering over a trinket

### ISSUE THREAD

**Issue by Knakriktsur** [raethkcj/RatingBuster#54]
I get this Error message. It gets more if i mouse over a trinket item. Any other item is fine.
Class Druid Feral
Game is BCC
Client language is german.
Addonversion is 1.2.2
Her it goes to 129 but if i hover over any more trinkets it rasies more...

"
129x RatingBuster\UTF8\utf8.lua:84: UTF-8 string terminated early
[string "=[C]"]: in function `error'
[string "@RatingBuster\UTF8\utf8.lua"]:84: in function <RatingBuster\UTF8\utf8.lua:59>
[string "@RatingBuster\UTF8\utf8.lua"]:171: in function `utf8len'
[string "@RatingBuster\UTF8\utf8.lua"]:209: in function <RatingBuster\UTF8\utf8.lua:189>
[string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua"]:4448: in function `GetSum'
[string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua"]:4908: in function `GetDiff'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:2805: in function `StatSummary'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1526: in function `handler'
[string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:191: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:185>
[string "=[C]"]: in function `SetCompareItem'
[string "@FrameXML\GameTooltip.lua"]:716: in function `GameTooltip_ShowCompareItem'
[string "@!MoncaiCompare\!MoncaiCompare-7.2.0.lua"]:48: in function <!MoncaiCompare\!MoncaiCompare.lua:46>
...
[string "=[C]"]: ?
[string "@Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua"]:434: in function <Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:428>
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:107: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML\ContainerFrame.lua"]:1352: in function `ContainerFrameItemButton_OnEnter'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:369: in function `ShowTooltip'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:340: in function `UpdateTooltip'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:180: in function <...faceBagnon\common\Wildpants\classes\item.lua:179>

Locals:
(*temporary) = "UTF-8 string terminated early"
"

**Comment by raethkcj** [comment]
Hi, there are a lot of addons in that stack trace. Can you try with just RatingBuster enabled?

If there's no error there, leave RatingBuster enabled and enable each of these addons one by one:
MoncaiCompare
Auc-Advanced
TradeSkillMaster
Bagnon

and let me know which combination of addons causes it.

**Comment by Knakriktsur** [comment]
Hi,
I`ll test this this weekend and let you know. Thanks for your response :)

**Comment by miehl** [comment]
So i had a similiar thing happen. I deactivated every addon besides this one. Class feral druid, Im playing on a german client. I hovered over the trinket "Mit Essenz erfüllter Pilz" (https://tbc.wowhead.com/item=28109/essence-infused-mushroom) and it threw two errors.
1)
Message: Interface\AddOns\RatingBuster\UTF8\utf8.lua:84: UTF-8 string terminated early
Time: Sat Jun 11 20:58:29 2022
Count: 1
Stack: Interface\AddOns\RatingBuster\UTF8\utf8.lua:84: UTF-8 string terminated early
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\RatingBuster\UTF8\utf8.lua"]:84: in function <Interface\AddOns\RatingBuster\UTF8\utf8.lua:59>
[string "@Interface\AddOns\RatingBuster\UTF8\utf8.lua"]:171: in function `utf8len'
[string "@Interface\AddOns\RatingBuster\UTF8\utf8.lua"]:209: in function <Interface\AddOns\RatingBuster\UTF8\utf8.lua:189>
[string "@Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua"]:4408: in function `GetSum'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:2844: in function `StatSummary'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:1567: in function `handler'
[string "@Interface\AddOns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?

Locals: (*temporary) = "UTF-8 string terminated early"

2)
Message: Interface\AddOns\RatingBuster\UTF8\utf8.lua:84: UTF-8 string terminated early
Time: Sat Jun 11 21:00:46 2022
Count: 99
Stack: Interface\AddOns\RatingBuster\UTF8\utf8.lua:84: UTF-8 string terminated early
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\RatingBuster\UTF8\utf8.lua"]:84: in function <Interface\AddOns\RatingBuster\UTF8\utf8.lua:59>
[string "@Interface\AddOns\RatingBuster\UTF8\utf8.lua"]:171: in function `utf8len'
[string "@Interface\AddOns\RatingBuster\UTF8\utf8.lua"]:209: in function <Interface\AddOns\RatingBuster\UTF8\utf8.lua:189>
[string "@Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua"]:4408: in function `GetSum'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:2844: in function `StatSummary'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:1567: in function `handler'
[string "@Interface\AddOns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1352: in function `UpdateTooltip'
[string "@Interface\FrameXML\GameTooltip.lua"]:429: in function <Interface\FrameXML\GameTooltip.lua:408>

Locals: (*temporary) = "UTF-8 string terminated early"

and shortly after that another one came in, while i was copying the messages it threw a third one: 
3) 
Message: Interface\AddOns\RatingBuster\UTF8\utf8.lua:84: UTF-8 string terminated early
Time: Sat Jun 11 21:00:42 2022
Count: 3
Stack: Interface\AddOns\RatingBuster\UTF8\utf8.lua:84: UTF-8 string terminated early
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\RatingBuster\UTF8\utf8.lua"]:84: in function <Interface\AddOns\RatingBuster\UTF8\utf8.lua:59>
[string "@Interface\AddOns\RatingBuster\UTF8\utf8.lua"]:171: in function `utf8len'
[string "@Interface\AddOns\RatingBuster\UTF8\utf8.lua"]:209: in function <Interface\AddOns\RatingBuster\UTF8\utf8.lua:189>
[string "@Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua"]:4408: in function `GetSum'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:2844: in function `StatSummary'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:1567: in function `handler'
[string "@Interface\AddOns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1352: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = "UTF-8 string terminated early"

**Comment by raethkcj** [comment]
Thanks for the additional input! Looks like it was a pretty niche error on certain items with unicode characters occuring before a period, i.e. the `ä` in ` gewährt.`.

Let me know if any problems remain!
