### ISSUE TITLE
Tooltip window - grows horizontally 

### ISSUE THREAD

**Issue by Jorvanus** [raethkcj/RatingBuster#55]
Hey, since most recent update, the tooltip spreads all the words out as far as it can go horizontally.  

Goes from 
![image](https://user-images.githubusercontent.com/89010934/141431568-be441657-200c-4780-b8bd-4773309bbb4e.png)

to
![image](https://user-images.githubusercontent.com/89010934/141431606-91a0f9fb-8b52-4098-a855-d9e769cdf271.png)

**Comment by Jorvanus** [comment]
With literally only ratingbuster on 

![image](https://user-images.githubusercontent.com/89010934/141526257-b55a2764-5b06-438e-973e-ba3d85920ac7.png)

**Comment by Dephi73** [comment]
same he
![WoWScrnShot_111321_002905](https://user-images.githubusercontent.com/41539679/141595197-b9830fbe-6ddf-478f-8896-9c73b9c3cab9.jpg)
re

**Comment by Dephi73** [comment]
![WoWScrnShot_111321_003247](https://user-images.githubusercontent.com/41539679/141595368-bcc29751-6c39-44ad-b898-3d23dd9f7a12.jpg)

**Comment by raethkcj** [comment]
Should be fixed, let me know if anything weird remains.
