### ISSUE TITLE
Cant disable summary showing

### ISSUE THREAD

**Issue by KonstantinosKoubetsos** [raethkcj/RatingBuster#6]
/rb sum show
/rb sum hide 
Unknown arguments
and i dont see any other commande to turn off the summary

Edit: line 509 in the .lua, the toggle option is _showSum_ when the description says it should be _show_

**Comment by raethkcj** [comment]
This was mostly a documentation  error, correct syntax will be `/rb sum showSum`. The README was updated.

You can also change this in the options menu without slash commands by the way, just `/rb` by itself will open the menu.
