### ISSUE TITLE
Dodge rating in local French

### ISSUE THREAD

**Issue by featoner** [raethkcj/RatingBuster#60]
Hello

we have an issue with the Dodge rating in the french version.

It doesn't works fine, seems to not detect the rating on item so addon display 0 and we can't compare items very well.

Sorry for my bad english hope u can fix it soon :)

Thx a lot
![WoWScrnShot_010222_183345_LI](https://user-images.githubusercontent.com/96992574/147884330-611e2368-54db-40f9-8029-2e33e72e0890.jpg)

**Comment by raethkcj** [comment]
Closed #62
