### ISSUE TITLE
Can you provide the addon on curse please? Thanks a lot.

### ISSUE THREAD

**Issue by baaatzi** [raethkcj/RatingBuster#63]
Can you provide the addon on curse please? Thanks a lot.

**Comment by WolfxUdK** [comment]
Will be helpful for updating purposes

**Comment by raethkcj** [comment]
After reading Overwolf's anticompetitive stance [here](https://medium.com/overwolf/update-on-curseforge-api-180468476253), I can't in good faith support Overwolf/Curseforge.

WowUp supports updating directly from GitHub Releases, and I also publish my releases to Wago.
