### ISSUE TITLE
Error when equipping protection paladin 4 piece tier 6 

### ISSUE THREAD

**Issue by gukle** [raethkcj/RatingBuster#64]
269x ...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua:143: attempt to index field '?' (a nil value)
[string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua"]:143: in function <...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:131>
[string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua"]:2874: in function `GetStatMod'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:2041: in function `func'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:2867: in function `StatSummary'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1524: in function `handler'
[string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@EPGP-Classic\libs\AceHook-3.0\AceHook-3.0-9.lua"]:95: in function <EPGP-Classic\libs\AceHook-3.0\AceHook-3.0.lua:87>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:107: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML\ContainerFrame.lua"]:1352: in function `ContainerFrameItemButton_OnEnter'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:369: in function `ShowTooltip'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:340: in function `UpdateTooltip'
[string "@FrameXML\GameTooltip.lua"]:435: in function <FrameXML\GameTooltip.lua:414>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
t = <table> {
}
set = 554
(for index) = 1
(for limit) = 19
(for step) = 1
i = 1
itemID = 30987
name = "Primal Mooncloth"
itemLink = "|cffa335ee|Hitem:30987:3002:24033:25896:::::70:::::::::|h[Lightbringer Faceguard]|h|r"
(for index) = 31
(for limit) = 31
(for step) = 1
j = 31
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Disenchanting requires Enchanting (300)"
(*temporary) = "Primal Mooncloth"
(*temporary) = "attempt to index field '?' (a nil value)"
item_set_cache = <table> {
}
tip = StatLogicTooltip {
 1 = StatLogicTooltipTextLeft1 {
 }
 2 = StatLogicTooltipTextLeft2 {
 }
 3 = StatLogicTooltipTextLeft3 {
 }
 4 = StatLogicTooltipTextLeft4 {
 }
 5 = StatLogicTooltipTextLeft5 {
 }
 6 = StatLogicTooltipTextLeft6 {
 }
 7 = StatLogicTooltipTextLeft7 {
 }
 8 = StatLogicTooltipTextLeft8 {
 }
 9 = <unnamed> {
 }
 10 = <unnamed> {
 }
 11 = <unnamed> {
 }
 12 = <unnamed> {
 }
 13 = <unnamed> {
 }
 14 = <unnamed> {
 }
 15 = <unnamed> {
 }
 16 = <unnamed> {
 }
 17 = <unnamed> {
 }
 18 = <unnamed> {
 }
 19 = <unnamed> {
 }
 20 = <unnamed> {
 }
 21 = <unnamed> {
 }
 22 = <unnamed> {
 }
 23 = <unnamed> {
 }
 24 = <unnamed> {
 }
 25 = <unnamed> {
 }
 26 = <unnamed> {
 }
 27 = <unnamed> {
 }
 28 = <unnamed> {
 }
 29 = <unnamed> {
 }
 30 = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\SharedTooltipTemplates.lua:194
 NineSlice = <unnamed> {
 }
 layoutType = "TooltipDefaultLayout"
 0 = <userdata>
 TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:163
 TopOverlay = <unnamed> {
 }
 GetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:182
 updateTooltip = 0.200000
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:178
 GetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:190
 SetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:186
}

**Comment by palla447** [comment]
i am experiencing this same issue.
the error appears to occur after equipping any paladin t6 items. the error does not appear to occur while item is in the player bag or bank

> Date: 2022-02-03 18:39:39
> 
> ID: 1
> Error occured in: Global
> Count: 1
> Message: ...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua line 143:
>    attempt to index field '?' (a nil value)
> Debug:
>    [string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua"]:143:
>       ...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:131
>    [string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua"]:2874: GetStatMod()
>    [string "@RatingBuster\RatingBuster.lua"]:1774:
>       RatingBuster\RatingBuster.lua:1561
>    [string "=(tail call)"]: ?
>    [string "@RatingBuster\RatingBuster.lua"]:1435: handler()
>    [string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua"]:156:
>       ...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150
>    [string "=[C]"]: ?
>    [string "=[C]"]: ?
>    [string "=[C]"]: SetBagItem()
>    [string "@..\FrameXML\ContainerFrame.lua"]:1352: ContainerFrameItemButton_OnEnter()
>    [string "@Bagnon\common\Wildpants\classes\item.lua"]:369: ShowTooltip()
>    [string "@Bagnon\common\Wildpants\classes\item.lua"]:340: UpdateTooltip()
>    [string "@Bagnon\common\Wildpants\classes\item.lua"]:180:
>       ...face\AddOns\Bagnon\common\Wildpants\classes\item.lua:179
> Locals:
> t = <table> {
> }
> set = 552
> (for index) = 5
> (for limit) = 19
> (for step) = 1
> i = 5
> itemID = 30991
> name = "Wrath of Spellfire"
> itemLink = "|cffa335ee|Hitem:30991:2659:32200:32200:32200::::70:::::::::|h[Lightbringer Chestguard]|h|r"
> (for index) = 31
> (for limit) = 31
> (for step) = 1
> j = 31
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "(2) Set: Increases the mana gained from your Spiritual Attunement ability by 10%."
> (*temporary) = "Wrath of Spellfire"
> (*temporary) = "attempt to index field '?' (a nil value)"
> item_set_cache = <table> {
> }
> tip = StatLogicTooltip {
>  1 = StatLogicTooltipTextLeft1 {
>  }
>  2 = StatLogicTooltipTextLeft2 {
>  }
>  3 = StatLogicTooltipTextLeft3 {
>  }
>  4 = StatLogicTooltipTextLeft4 {
>  }
>  5 = StatLogicTooltipTextLeft5 {
>  }
>  6 = StatLogicTooltipTextLeft6 {
>  }
>  7 = StatLogicTooltipTextLeft7 {
>  }
>  8 = StatLogicTooltipTextLeft8 {
>  }
>  9 = <unnamed> {
>  }
>  10 = <unnamed> {
>  }
>  11 = <unnamed> {
>  }
>  12 = <unnamed> {
>  }
>  13 = <unnamed> {
>  }
>  14 = <unnamed> {
>  }
>  15 = <unnamed> {
>  }
>  16 = <unnamed> {
>  }
>  17 = <unnamed> {
>  }
>  18 = <unnamed> {
>  }
>  19 = <unnamed> {
>  }
>  20 = <unnamed> {
>  }
>  21 = <unnamed> {
>  }
>  22 = <unnamed> {
>  }
>  23 = <unnamed> {
>  }
>  24 = <unnamed> {
>  }
>  25 = <unnamed> {
>  }
>  26 = <unnamed> {
>  }
>  27 = <unnamed> {
>  }
>  28 = <unnamed> {
>  }
>  29 = <unnamed> {
>  }
>  30 = <unnamed> {
>  }
>  SetBorderBlendMode = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:194
>  NineSlice = <unnamed> {
>  }
>  layoutType = "TooltipDefaultLayout"
>  0 = <userdata>
>  TooltipBackdropOnLoad = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:163
>  TopOverlay = <unnamed> {
>  }
>  GetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:182
>  updateTooltip = 0.200000
>  needsReset = true
>  BottomOverlay = <unnamed> {
>  }
>  SetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:178
>  GetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:190
>  SetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:186
> }
> 
> AddOns:
>   Swatter, v1.13.6652 (SwimmingSeadragon)
>   Aptechka, v9.1.5-tbc
>   AtlasLootClassic, vv2.4.1-bcc
>   AtlasLootClassicData, vv2.4.1-bcc
>   AtlasLootClassicDungeonsAndRaids, vv2.4.1-bcc
>   Bagnon, v9.1.4
>   Clique, vv3.1.2
>   DBMCore, v99722e9
>   DBMStatusBarTimers, v99722e9
>   ElvUI, v2.33
>   FarmHud, v8.8.0-release
>   FarmHudQuestArrow, v8.8.0-release
>   FishingBuddy, v0.7.5.2
>   GatherMate2, v1.46.1-classic
>   JunkFilter, v2.00
>   LeatrixPlus, v2.5.85
>   LFGBulletinBoard, v2.61
>   MikScrollingBattleText, v5.7.153
>   Molinari, v90100.79-Release
>   NovaInstanceTracker, v1.26
>   PallyPower, vv1.4.1-classic
>   Questie, v6.8.2
>   RatingBuster, v
>   Routes, vv1.6.6-5-g05cff6e
>   SlideBar, v1.13.6726 (SwimmingSeadragon)
>   SpellCalc, v0.12
>   Stubby, v1.13.6614 (SwimmingSeadragon)
>   Talented, vv211202
>   TalentedData, v
>   ThreatClassic2, v2.41
>   TidyPlatesThreatPlates, v10.2.2
>   TomTom, vv3.0.1
>   WeakAuras, v3.7.5
>   WIM, v3.9.4
>   WIMElvUISkin, v20501.01-BBC
>   BlizRuntimeLib_enUS v2.5.3.20503 <none>
>   (ck=3d6)

**Comment by raethkcj** [comment]
Thanks, should be fixed.
