### ISSUE TITLE
Error when Lightbringer Chestguard Equipped

### ISSUE THREAD

**Issue by Blackl1st** [raethkcj/RatingBuster#65]
Addon stops displaying on helm, shoulder, gloves, pants, chest tooltip if I have Lightbringer Chestguard equipped. Also get the error below. I have already tried disabling TSM and Itemrack. Any suggestions?

6054x ...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua:143: attempt to index field '?' (a nil value)
[string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua"]:143: in function <...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:131>
[string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua"]:2874: in function `GetStatMod'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1774: in function <RatingBuster\RatingBuster.lua:1561>
[string "=(tail call)"]: ?
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1435: in function `handler'
[string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:107: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105>
[string "=[C]"]: in function `SetBagItem'
[string "@ItemRack\ItemRack-3.69.nil.lua"]:1532: in function `func'
[string "@ItemRack\ItemRack-3.69.nil.lua"]:905: in function `OnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
t = <table> {
}
set = 552
(for index) = 5
(for limit) = 19
(for step) = 1
i = 5
itemID = 30991
name = "Wrath of Spellfire"
itemLink = "|cffa335ee|Hitem:30991:2659:32196:32196:32221::::70:::::::::|h[Lightbringer Chestguard]|h|r"
(for index) = 31
(for limit) = 31
(for step) = 1
j = 31
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Set: Increases the mana gained from your Spiritual Attunement ability by 10%."
(*temporary) = "Wrath of Spellfire"
(*temporary) = "attempt to index field '?' (a nil value)"
item_set_cache = <table> {
}
tip = StatLogicTooltip {
 1 = StatLogicTooltipTextLeft1 {
 }
 2 = StatLogicTooltipTextLeft2 {
 }
 3 = StatLogicTooltipTextLeft3 {
 }
 4 = StatLogicTooltipTextLeft4 {
 }
 5 = StatLogicTooltipTextLeft5 {
 }
 6 = StatLogicTooltipTextLeft6 {
 }
 7 = StatLogicTooltipTextLeft7 {
 }
 8 = StatLogicTooltipTextLeft8 {
 }
 9 = <unnamed> {
 }
 10 = <unnamed> {
 }
 11 = <unnamed> {
 }
 12 = <unnamed> {
 }
 13 = <unnamed> {
 }
 14 = <unnamed> {
 }
 15 = <unnamed> {
 }
 16 = <unnamed> {
 }
 17 = <unnamed> {
 }
 18 = <unnamed> {
 }
 19 = <unnamed> {
 }
 20 = <unnamed> {
 }
 21 = <unnamed> {
 }
 22 = <unnamed> {
 }
 23 = <unnamed> {
 }
 24 = <unnamed> {
 }
 25 = <unnamed> {
 }
 26 = <unnamed> {
 }
 27 = <unnamed> {
 }
 28 = <unnamed> {
 }
 29 = <unnamed> {
 }
 30 = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\SharedTooltipTemplates.lua:194
 NineSlice = <unnamed> {
 }
 layoutType = "TooltipDefaultLayout"
 0 = <userdata>
 TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:163
 TopOverlay = <unnamed> {
 }
 GetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:182
 updateTooltip = 0.200000
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:178
 GetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:190
 SetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:186
}

**Comment by raethkcj** [comment]
This should have been fixed in 1.3.2, make sure to update!

https://github.com/raethkcj/RatingBuster/releases/tag/1.3.2

Dupe #64
