### ISSUE TITLE
a thank you (and a request) :D

### ISSUE THREAD

**Issue by frosty939** [raethkcj/RatingBuster#69]
### The Thank You

i just wanted to give a huge <3 to you for porting this! i missed this mod so much, i can't even begin to tell you how stoked i was when it actually popped up when i searched for it on wowup.. thank you! :D

it was one of the many addons i loved back in the day, but that seem to get looked over now due to everyone just blinding following bis lists lol

---
### The Request

Is there any chance you'd be willing to take a look at the old [DrDamage ](https://www.curseforge.com/wow/addons/dr-damage) addon and see if it's something you could port over as well?

Or could you tell me what would need to be done to get it working again? I don't even know where to begin to try to fix it myself :/
_(i realize that might be a complicated question/answer, so dont worry if you dont have the time to explain how i could fix it myself)_

**Comment by Lackadaisical18** [comment]
An addon with similar functionality to DrDamage (as far as I can tell having never used Dr) is SpellCalc, which works in TBC classic: https://github.com/coolmodi/SpellCalc

**Comment by raethkcj** [comment]
Hey, thanks for the feedback! I enjoy many of these older addons too, but my time to work on them is limited, so I'm not looking to port any more for now. Hopefully the suggested alternative works for you!
