### ISSUE TITLE
1.3.7 broke ratings percentages in gear tooltips

### ISSUE THREAD

**Issue by Hantunaar** [raethkcj/RatingBuster#72]
Hey so latest update (1.3.7) broke percentages in gear tooltips in french, and probably others non-english clients.

Green lines like "Equip: Improves spell hit rating by 17" no longer display the percentage value of ratings.

According to patch changes, this is related with the line _{pattern = " de (%d+)[^%%]?$", addInfo = "AfterNumber",},_ and more exactly with the $ thing. Removing it brought back the percentages, but whatever it did somewhere else might be clunky now.

Also, if work has to be done there, could it be possible to add a blankspace after the percentages? So it doesn't stick to the next word.

**Comment by raethkcj** [comment]
Sorry about that, working on a fix. 

I only just installed frFR locale, but I see your point about percentages sticking to the next word. So I'll fix that as well.

Just for context, the reason I'm modifying these is to fix a handful of items that are incorrectly converting percentages to rating, for example:
![image](https://user-images.githubusercontent.com/7716908/159191980-81247011-d624-4ee1-ae26-865fa6b02904.png)

In hindsight, adding `$` was a bad idea, but I think I can fix it by breaking it into two separate patterns.
