### ISSUE TITLE
Avoidance summary wrong?

### ISSUE THREAD

**Issue by voshond** [raethkcj/RatingBuster#73]
I've been playing protection Paladin since P1 now and I noticed that some items the total avoidance is higher then what is actually converted.

I'm using the avoidance macro to calculate as well as a weak-aura to do the same calculation. These all seem to be working just fine.

However when I'm switching items that supposed to have a higher avoidance based on RatingBuster, the results of the avoidance calculators show the item is worse. Maybe there is a different calculation on avoidance for Prot-Paladins?

![Example](https://i.imgur.com/cKS4pFw.png)

Here is my avoidance without the eterium bracers, that supposed to have much higher avoidance, right?
![Without Eternium Shell Bracers](https://i.imgur.com/woILdOX.png)

And here with the "upgrade"
![With Eternium Shell Bracers](https://i.imgur.com/sJpV9Ee.png)

Either the avoidance summary is "wrong" or I misunderstood it. In that case I'd like to request that maybe we get a "Total Avoidance % Summary", that would show me the exact avoidance I would get per item, so I can easily see if an item would be an actual upgrade.

Cheers

**Comment by raethkcj** [comment]
Shield block isn't included in Avoidance Summary by default, but there is a checkbox to include it.

Some players refer to shield block as "mitigation" rather than "avoidance" because you're not actually avoiding the attack.

Honestly this difference of terminology was used more in 2007 than 2022, so I wouldn't mind changing the default.

**Comment by voshond** [comment]
Thanks for the clarification!
I also did now find the checkbox, which resolves my issue. Cheers!
