### ISSUE TITLE
Do RB handles Stats from % of other stats bonuses?

### ISSUE THREAD

**Issue by Hantunaar** [raethkcj/RatingBuster#74]
Hey I was wondering if RatingBuster handles stats like tailoring Spellfire bonus set: "_Increases spell damage by up to 7% of your total Intellect._" https://tbc.wowhead.com/item=21848/spellfire-robe

Also the incoming P5 gem Ember Skyfire Diamond effect: "_+14 Spell Damage & +2% Intellect_" https://tbc.wowhead.com/item=35503/ember-skyfire-diamond

I know there is something called THREAT_MOD within the code for threat enchants but I don't think it works the same way?

**Comment by raethkcj** [comment]
Hi,

Spellfire set is handled if you equip 3 pieces of the set.

Ember Skyfire Diamond is not handled, but most of the other % intellect effects are handled; talents for Mage, Paladin, Priest, Druid, as well as Blessing of Kings and the racial for Gnomes. I'll look into adding the gem.

I think THREAT_MOD is unused, the original author probably planned to use it in 2008 but never got around to it in this addon.
