### ISSUE TITLE
Rating buster just stops working on one character.

### ISSUE THREAD

**Issue by vertx66** [raethkcj/RatingBuster#77]
Hi there, 

Don't really know how to explain it other than what I've experienced below, not sure if others have too. 

I load the add-on. Works fine for a day or two specifically on this character. aka the tool tip functions fine as below where I can compare items

![image](https://user-images.githubusercontent.com/75558294/163705291-6a3d2c2c-515f-4625-8a53-54413241dbb1.png)

Then a few days later, its just gone. Add-on is loaded, works on other characters on the account fine, running all the same add-ons.

Only way to get it working again is delete the files in Saved Variables for the account of Rating Buster.

Happy to do more testing if you can supply any detail.

Thanks
Vert

**Comment by vertx66** [comment]
Sorry to clarify; The "Stat summary" function just ceases to work / exist even though the setting is enabled on the profile, regardless of the profile selected. (Tried creating new ones)

**Comment by vertx66** [comment]
So I log out of my Shaman, log over to mage. still working on mage. Log back onto Shaman. Broken again

![image](https://user-images.githubusercontent.com/75558294/163705702-3b3a8bb5-79ad-4387-906c-4f3046496671.png)

**Comment by raethkcj** [comment]
Do you have Lua errors enabled?

`/console scriptErrors 1`

Or install BugSack and BugGrabber for easy error collecting.

Maybe also attach the full broken SavedVariables file for RatingBuster.

**Comment by vertx66** [comment]
Hey thanks for the reply. I will grab the broken SV file and attach it later. I will also enabled the errors and download a copy of BugGrabber and see what I can collect. 
I just used the cloak as an example, the whole module just doesnt even load. I will try get more data for you. Thanks

**Comment by vertx66** [comment]
First error when logging in (stats module working)

`73x ...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua:143: attempt to index field '?' (a nil value)
[string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua"]:143: in function <...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:131>
[string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua"]:2874: in function `GetStatMod'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:2041: in function `func'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:2867: in function `StatSummary'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1524: in function `handler'
[string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:107: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@TBag\TBag-2.5.2.1.lua"]:2176: in function `SetInventoryItem'
[string "@TBag\Buttons.lua"]:46: in function `OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
t = <table> {
}
set = 554
(for index) = 5
(for limit) = 19
(for step) = 1
i = 5
itemID = 31017
name = "Primal Mooncloth"
itemLink = "|cffa335ee|Hitem:31017:2661:32196:32196:32196::::70:::::::::|h[Skyshatter Breastplate]|h|r"
(for index) = 31
(for limit) = 31
(for step) = 1
j = 31
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Set: Whenever you have an air totem, an earth totem, a fire totem, and a water totem active at the same time, you gain 15 mana per 5 sec, 35 spell critical strike rating, and up to 45 spell damage."
(*temporary) = "Primal Mooncloth"
(*temporary) = "attempt to index field '?' (a nil value)"
item_set_cache = <table> {
}
tip = StatLogicTooltip {
 1 = StatLogicTooltipTextLeft1 {
 }
 2 = StatLogicTooltipTextLeft2 {
 }
 3 = StatLogicTooltipTextLeft3 {
 }
 4 = StatLogicTooltipTextLeft4 {
 }
 5 = StatLogicTooltipTextLeft5 {
 }
 6 = StatLogicTooltipTextLeft6 {
 }
 7 = StatLogicTooltipTextLeft7 {
 }
 8 = StatLogicTooltipTextLeft8 {
 }
 9 = <unnamed> {
 }
 10 = <unnamed> {
 }
 11 = <unnamed> {
 }
 12 = <unnamed> {
 }
 13 = <unnamed> {
 }
 14 = <unnamed> {
 }
 15 = <unnamed> {
 }
 16 = <unnamed> {
 }
 17 = <unnamed> {
 }
 18 = <unnamed> {
 }
 19 = <unnamed> {
 }
 20 = <unnamed> {
 }
 21 = <unnamed> {
 }
 22 = <unnamed> {
 }
 23 = <unnamed> {
 }
 24 = <unnamed> {
 }
 25 = <unnamed> {
 }
 26 = <unnamed> {
 }
 27 = <unnamed> {
 }
 28 = <unnamed> {
 }
 29 = <unnamed> {
 }
 30 = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\SharedTooltipTemplates.lua:194
 NineSlice = <unnamed> {
 }
 layoutType = "TooltipDefaultLayout"
 0 = <userdata>
 TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:163
 TopOverlay = <unnamed> {
 }
 GetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:182
 updateTooltip = 0.200000
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:178
 GetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:190
 SetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:186
}
`



Logging out and switching to alt then back to shaman, tooltips stop working

`116x ...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua:143: attempt to index field '?' (a nil value)
[string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua"]:143: in function <...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:131>
[string "@RatingBuster\libs\StatLogic-1.0\StatLogic-1.0-78899.lua"]:2874: in function `GetStatMod'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:2041: in function `func'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:2867: in function `StatSummary'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1524: in function `handler'
[string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:107: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@TBag\TBag-2.5.2.1.lua"]:2176: in function `SetInventoryItem'
[string "@TBag\Buttons.lua"]:46: in function `OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
t = <table> {
}
set = 554
(for index) = 5
(for limit) = 19
(for step) = 1
i = 5
itemID = 31017
name = "Primal Mooncloth"
itemLink = "|cffa335ee|Hitem:31017:2661:32196:32196:32196::::70:::::::::|h[Skyshatter Breastplate]|h|r"
(for index) = 31
(for limit) = 31
(for step) = 1
j = 31
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Set: Whenever you have an air totem, an earth totem, a fire totem, and a water totem active at the same time, you gain 15 mana per 5 sec, 35 spell critical strike rating, and up to 45 spell damage."
(*temporary) = "Primal Mooncloth"
(*temporary) = "attempt to index field '?' (a nil value)"
item_set_cache = <table> {
}
tip = StatLogicTooltip {
 1 = StatLogicTooltipTextLeft1 {
 }
 2 = StatLogicTooltipTextLeft2 {
 }
 3 = StatLogicTooltipTextLeft3 {
 }
 4 = StatLogicTooltipTextLeft4 {
 }
 5 = StatLogicTooltipTextLeft5 {
 }
 6 = StatLogicTooltipTextLeft6 {
 }
 7 = StatLogicTooltipTextLeft7 {
 }
 8 = StatLogicTooltipTextLeft8 {
 }
 9 = <unnamed> {
 }
 10 = <unnamed> {
 }
 11 = <unnamed> {
 }
 12 = <unnamed> {
 }
 13 = <unnamed> {
 }
 14 = <unnamed> {
 }
 15 = <unnamed> {
 }
 16 = <unnamed> {
 }
 17 = <unnamed> {
 }
 18 = <unnamed> {
 }
 19 = <unnamed> {
 }
 20 = <unnamed> {
 }
 21 = <unnamed> {
 }
 22 = <unnamed> {
 }
 23 = <unnamed> {
 }
 24 = <unnamed> {
 }
 25 = <unnamed> {
 }
 26 = <unnamed> {
 }
 27 = <unnamed> {
 }
 28 = <unnamed> {
 }
 29 = <unnamed> {
 }
 30 = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\SharedTooltipTemplates.lua:194
 NineSlice = <unnamed> {
 }
 layoutType = "TooltipDefaultLayout"
 0 = <userdata>
 TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:163
 TopOverlay = <unnamed> {
 }
 GetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:182
 updateTooltip = 0.200000
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:178
 GetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:190
 SetBackdropBorderColor = <function> defined @SharedXML\SharedTooltipTemplates.lua:186
}
`




SV attached, probably wont show any issue. I noticed if I kill the game, start again. Shaman's tooltips work again

`
RatingBusterDB = {
	["profileKeys"] = {
		["Vertx - Arugal"] = "profile",
		["Fckwitvert - Arugal"] = "VertSham",
		["Vrt - Arugal"] = "profile",
	},
	["profiles"] = {
		["profile"] = {
			["showItemID"] = true,
		},
		["VertSham"] = {
			["showItemID"] = true,
		},
	},
}
`

**Comment by raethkcj** [comment]
Hmm, it looks like you might not be running the latest version of RatingBuster. Can you make sure you're on version 1.3.8? Should fix this issue I believe.

**Comment by vertx66** [comment]
No worries will do. Not sure how I missed that one. thank you.
