### ISSUE TITLE
ItemLevel bounces (appears and disappears) on Tooltip mouseover for some items

### ISSUE THREAD

**Issue by boktai1000** [raethkcj/RatingBuster#80]
Issue description:

When mousing over some items, the ItemLevel portion of the tooltip flickers (almost looks like it is bouncing) on the item while quickly appearing and disappearing.

A screenshot of my relevant settings are as follows, and currently using the latest version 1.4.2 although it has certainly been happening for a while / few versions now.

Problem (Imagine a gif of this)
![image](https://user-images.githubusercontent.com/9054563/174427724-3a1e4a11-c431-4480-9fb0-d6bedef8a4f8.png)
![image](https://user-images.githubusercontent.com/9054563/174427733-01be051f-689a-4428-a054-23457b3dfbf5.png)

Settings
![image](https://user-images.githubusercontent.com/9054563/174427642-8e4b5bdb-9421-4cfc-8c21-89e03d0f30b6.png)
![image](https://user-images.githubusercontent.com/9054563/174427649-714c4b54-0923-49b9-b571-528c32899a1d.png)
![image](https://user-images.githubusercontent.com/9054563/174427659-b6a9e19e-1df4-4cef-bea9-0dbb8770baac.png)
![image](https://user-images.githubusercontent.com/9054563/174427669-ff2ccb09-dc07-40cd-8bcc-0681f9b45786.png)
![image](https://user-images.githubusercontent.com/9054563/174427680-b57b4890-84df-4976-959b-133f7c28bb41.png)

Version of RatingBuster: 1.4.2
Version of World of Warcraft: 2.5.4 BC Classic

**Comment by raethkcj** [comment]
Thanks, were you seeing this issue on any type of recipe besides Grimoires?

**Comment by boktai1000** [comment]
I'll open a new issue if I come across anything. I do think I may have seen something else, but when I noticed it this time I was like okay - I should probably report this.
