### ISSUE TITLE
Item's stats shown in summary scale with percentage buffs currently on the player

### ISSUE THREAD

**Issue by Lackadaisical18** [raethkcj/RatingBuster#81]
To reproduce:

- Mouseover a piece of gear, noting the total stats shown in the summary.
- Acquire a buff that alters your stats by a percentage (easy mode: Blessing of Kings).
- Look at the same piece of gear; the stat summary shows different totals now!

My best guess is that this comes from accounting for the paladin Divine Strength talent (+10% str), as that bonus is properly reflected in the stat summary for all gear with strength when talented into it.

I did not test this with anything besides Kings but I presume any percentage buff or malus would have the same effect. I did test with non-paladin characters and got the same results. As expected, things like crit from rating and ap from flat ap do not scale this way. Screenshots available upon request, version is current with GitHub.

I suppose this could be intended, but a player who doesn't know about this interaction could be confused by the changing numbers on static items.

**Comment by raethkcj** [comment]
Hi, this is indeed an intended feature of the addon. It's especially helpful for things like Druid forms, where stats like agility have different multipliers and conversions in each form.
