### ISSUE TITLE
Wrath classic support

### ISSUE THREAD

**Issue by soapnrope** [raethkcj/RatingBuster#82]
Hi, any plans to update this for Wrath classic? At quick glance seems like wrath classic runs more closer to like on retail client side therefore lot of changes might be required. 

Anyhow here are some errors you get on wrath classic beta right now:

Message: ...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3876: attempt to perform arithmetic on field '?' (a nil value)
Time: Sat Jul 23 15:10:04 2022
Count: 1
Stack: ...ns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3876: attempt to perform arithmetic on field '?' (a nil value)
[string "@Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua"]:3876: in function `GetNormalManaRegenFromSpi'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:2087: in function `func'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:2914: in function `StatSummary'
[string "@Interface\AddOns\RatingBuster\RatingBuster.lua"]:1567: in function `handler'
[string "@Interface\AddOns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "@Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua"]:508: in function <...ce\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua:502>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\Informant\Libs\LibExtraTip\LibExtraTip.lua"]:434: in function `SetBagItem'
[string "@Interface\AddOns\ArkInventory\Core\ArkInventory.lua"]:8157: in function `Frame_Item_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: self = <table> {
 GetRAPFromAgi = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3328
 GetReductionFromArmor = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:2857
 GetClassIDFromName = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:439
 GetSum = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:4177
 argCheck = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:75
 GetRAPPerAgi = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3289
 GetStatMod = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:2832
 GetRatingIDFromName = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:538
 tip = StatLogicTooltip {
 }
 ModEnchantGem = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3967
 RemoveGem = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3949
 GetBlockValueFromStr = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3146
 GetStatNameFromID = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:443
 RemoveEnchantGem = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3958
 RemoveEnchant = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3940
 GetBlockValuePerStr = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3108
 GetAPFromAgi = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3239
 GetNormalManaRegenFromSpi = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3859
 GetDiff = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:4823
 GetAPPerAgi = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3197
 GetHealthRegenFromSpi = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:3920
 GetEffectFromRating = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:2962
 StatTable = <table> {
 }
 PatternTest = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:4939
 Bench = <function> defined @Interface\AddOns\RatingBuster\libs\StatLogic-1.0\StatLogic-1.0.lua:4919
 GetDodgePerAgi = <function> defined @In

**Comment by raethkcj** [comment]
Hi! I am working on wrath support. I do have beta but it will take some time. I want to make sure the addon remains compatible with TBC rather than just copying the 3.3.5 values over the top.

**Comment by raethkcj** [comment]
Hi! I've begun releasing alpha builds with Wrath support: https://github.com/raethkcj/RatingBuster/releases/

So I'm going to close this issue. In addition to the changelogs there I posted a list of Known Issues to be aware of if you're interested in using it before launch: https://github.com/raethkcj/RatingBuster/issues/85
