### ISSUE TITLE
[Wrath Classic] Known Issues

### ISSUE THREAD

**Issue by raethkcj** [raethkcj/RatingBuster#85]
If you encounter an issue *not* on this list, please create a New Issue.

Comment on this issue if you have additional information or questions about the existing Known Issues.

## Known Issues
- ~~Ratings that affect both physical attacks and spells are only showing their effect for physical attacks.~~
  - ~~Summaries implemented, breakdowns still missing.~~
- ~~Spell power is not being added to stat summaries.~~
- ~~Armor penetration is added to summaries, but not breakdowns.~~
- ~~The options to see the effect of diminishing returns on avoidance are not yet functional.~~
  - Now only missing toggles to add pre-DR summaries
- [The descriptions for several Stat Breakdown settings include duplicate talent/buff names](https://github.com/raethkcj/RatingBuster/issues/146)
- ~~Default settings for Stat Breakdowns and Stat Summaries don't include most class-specific effects. The settings still work if manually toggled.~~
- [Buffs that stack, but whose unique effects should not stack, are currently stacking (e.g. Blessing of Kings and Blessing of Sanctuary)](https://github.com/raethkcj/RatingBuster/issues/145)
- ~~Ranged-specific hit, crit, and haste from scopes is not accounted for~~ (Vanilla: Includes hit scope)
- ~~Abomination's Might and Unleashed Rage are not properly calculated if the player is the only one providing the buff.~~
- [Shamans with Mental Quickness/Mental Dexterity will not see spell power from ~~Agility or~~ Intellect](https://github.com/raethkcj/RatingBuster/issues/147)
- ~~Items with green bonus armor are treated as if the full amount of armor is multiplied by Toughness, etc. when calculating AP bonuses for Bladed Armor / Armored to the Teeth. Armor on accessory items like rings is handled correctly.~~

**Comment by kylosandrax** [comment]
I have checked several items and I believe item enchants are also not being included in the calculation. Can this be added to the list of Known Issues?

![image](https://user-images.githubusercontent.com/6122480/188315754-214f7716-36e8-4a16-9fc9-c9b156cd1232.png)

Exported weights
```
( Pawn: v1: "Tank": ArmorPenetration=0.2, Stamina=1, DefenseRating=0.8, CritRating=0.2, Dps=10, Strength=0.33, ParryRating=0.58, ExpertiseRating=0.67, Agility=0.6, HitRating=0.67, HasteRating=0.2, Armor=0.05, MetaSocketEffect=24, DodgeRating=0.7, Ap=0.06 )
```

Manual Calculation
![image](https://user-images.githubusercontent.com/6122480/188315800-dc21fe77-de4f-470d-9727-3e2a9e385ea0.png)

**Comment by kylosandrax** [comment]
Observing the same with the +10 stam enchants

In-Game
![image](https://user-images.githubusercontent.com/6122480/188316700-de97eecf-32dc-4744-90bf-a8da7ca45118.png)

Manual Calculation
![image](https://user-images.githubusercontent.com/6122480/188316717-6191e2a6-197d-4841-b248-98e370c6116a.png)

Exactly 10 points out of sync, assuming that the 0.6 is being rounded up

**Comment by jebo80** [comment]
Hi, when we get spellpower update?

**Comment by raethkcj** [comment]
> Hi, when we get spellpower update?
> 
> I loaded the last update but I dont have spellpower :(

File a Bug Report

**Comment by raethkcj** [comment]
All issues resolved or moved to individual issues
