### ISSUE TITLE
[WotLKC] Error (Shaman only)

### ISSUE THREAD

**Issue by NayooZ** [raethkcj/RatingBuster#86]
Only comes up when i'm on my shaman - something to do with the spell damage conversions.

2x AceLocale-3.0-6: RatingBuster: Missing entry for '$value Dmg'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1845: in function <RatingBuster\RatingBuster.lua:1715>
[string "=(tail call)"]: ?
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1704: in function `SplitDoJoin'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1704: in function `SplitDoJoin'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1704: in function `SplitDoJoin'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1678: in function `ProcessLine'
[string "@RatingBuster\RatingBuster-1.3.8 (r$Revision: 78903 $).nil.lua"]:1560: in function `handler'
[string "@RatingBuster\libs\TipHooker-1.0\TipHooker-1.0-67029.lua"]:156: in function <...ns\RatingBuster\libs\TipHooker-1.0\TipHooker-1.0.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: ?

**Comment by raethkcj** [comment]
Thanks, fixed!
