### ISSUE TITLE
Item Enhancements not being calculated correctly

### ISSUE THREAD

**Issue by kylosandrax** [raethkcj/RatingBuster#88]
I have checked several items and I believe item enchants are also not being included in the calculation. 

Configured Weights
```
( Pawn: v1: "Tank": ArmorPenetration=0.2, Stamina=1, DefenseRating=0.8, CritRating=0.2, Dps=10, Strength=0.33, ParryRating=0.58, ExpertiseRating=0.67, Agility=0.6, HitRating=0.67, HasteRating=0.2, Armor=0.05, MetaSocketEffect=24, DodgeRating=0.7, Ap=0.06 )
```

In-Game Tooltip
![image](https://user-images.githubusercontent.com/6122480/188332248-1d6a5c4f-2872-47f5-a05e-e6863a90af75.png)

Manual Calculation
![image](https://user-images.githubusercontent.com/6122480/188332252-9442f546-7dd5-4d6d-bc68-2c64c10b91b2.png)

**Comment by kylosandrax** [comment]
2nd Example (Observing the same with the +10 stam enchants)

In-Game Tooltip
![image](https://user-images.githubusercontent.com/6122480/188332267-b112b269-4918-492c-ae44-61d949b7e0ef.png)

Manual Calculation
![image](https://user-images.githubusercontent.com/6122480/188332276-25c825de-68a5-49a8-834a-a168fd36513c.png)

**Comment by raethkcj** [comment]
As I said in the #87, the number you're circling is from Pawn, not RatingBuster.
