### ISSUE TITLE
Intense frame lag when hovering over items with Stat Summary enabled

### ISSUE THREAD

**Issue by WillowGryph** [raethkcj/RatingBuster#93]
If you hover over an item on your character sheet while the Stat Summary feature is enabled, your game freezes for half a second. Disabling the Stat Summary feature fixes this problem.

**Comment by raethkcj** [comment]
Could you share your locale, race, talents, and gear? There are a lot of variables that could affect this and it's definitely not a universal problem.

**Comment by WillowGryph** [comment]
https://user-images.githubusercontent.com/113316179/189762269-9d1bdf20-9525-4283-986f-7cb2e0bf15ed.mp4

Here's a quick video. All addons except RatingBuster were disabled.

**Comment by raethkcj** [comment]
I've pushed some performance changes in 1.5.6. Here are some examples of the reductions in CPU time I'm seeing. The -25% is likely just variance in testing, but `BuildGemmedTooltip`, `GetStatMod`, and `RemoveEnchant` are the functions I specifically targeted for improvement.
![image](https://i.imgur.com/Ag7RDyh.png)
