### ISSUE TITLE
[Bug]: Defense breakdown seems to be incorrect

### ISSUE THREAD

**Issue by Vishiswaz** [raethkcj/RatingBuster#98]
### Describe the bug

I think the addon is incorrect with regards to how much Dodge, Parry, Miss, and Block you get from Defense.

RatingBuster seems to think that the difference between Boots of the Righteous Path (23 defense rating) and Blue's Greaves of the Righteous Guardian (0 defense rating) is 0.39% in Dodge, Parry, and Miss, but when I actually equip the item, it changes each of these by 0.31%.

For the record:

- I tested this before gemming and Enchanting
- My total Defense (not rating) is 502 when Boots of the Righteous Path are equipped and 492 when Blue's Greaves are equipped.

### Addon Source

GitHub Releases

### Version

1.5.7

### Locale

English

### Talent Specialization

Protection Paladin

### Race

Human

**Comment by raethkcj** [comment]
Hmm, is your character's base defense skill capped? i.e. with no gear on, do you have 350/350 Defense skill for level 70?

**Comment by Vishiswaz** [comment]
Yes. 
![image](https://user-images.githubusercontent.com/78314117/191773666-df2befc3-15f6-4c20-8441-8172e48972f5.png)

**Comment by raethkcj** [comment]
Could you share your character sheet Defense tooltip with and without Blue's equipped?
e.g.
![image](https://user-images.githubusercontent.com/7716908/191783817-19eb6af0-4771-45a4-ab6b-0740f07a0d27.png)

**Comment by Vishiswaz** [comment]
Blues only? I'm mostly epic atm.

**Comment by Vishiswaz** [comment]
![image](https://user-images.githubusercontent.com/78314117/191784289-d8418a71-d419-411c-9029-2b60fc0e71f8.png)
without

**Comment by Vishiswaz** [comment]
![image](https://user-images.githubusercontent.com/78314117/191784387-82282010-4d44-4c2e-87b3-0278bfb6aa90.png)
With

**Comment by Vishiswaz** [comment]
Blue's doesn't give defense rating

**Comment by raethkcj** [comment]
I did mean the other one, sorry about that!

**Comment by Vishiswaz** [comment]
Well, since you already have the screenshot without, here's the one with the other boots equipped
![image](https://user-images.githubusercontent.com/78314117/191785863-d92fb471-d381-4ed8-90d1-ee7b53cc8565.png)

**Comment by raethkcj** [comment]
Ok, I'm seeing a difference of `6.08 - 5.68 = 0.4` which should just be a rounding difference, rather than the `0.31`

**Comment by Vishiswaz** [comment]
So that's very interesting. On the Defense tooltip, it matches RatingBuster, roughly 0.39%

But in reality, when you look at Dodge/Parry/Block, it's different, like 0.31%

**Comment by Vishiswaz** [comment]
I currently have a dodge gem now in the boots so let's just look at Parry.

With Boots of the Righteous Path:
![image](https://user-images.githubusercontent.com/78314117/191786589-e8c406c4-0f0e-401a-a5cf-ca0467489673.png)

With Blue's:
![image](https://user-images.githubusercontent.com/78314117/191786655-22a399c0-fbe1-4e9c-8f05-0895bae4940e.png)

**Comment by raethkcj** [comment]
Could be. IIRC the Stat Breakdown for Defense doesn't take DR into effect because it could end up being 3 different percentages, but the Stat Summary does.

**Comment by Vishiswaz** [comment]
So, RatingBuster is also missing that DR evaluation, then.

**Comment by raethkcj** [comment]
The Breakdown ignores DR to keep tooltips uncluttered; if you turn on the Stat Summary for Sum Parry Chance, you should get the amount after DR:
![image](https://i.imgur.com/MBC3eC0.png)

**Comment by Vishiswaz** [comment]
There's a decent chance that Block chance, in addition to Dodge chance and Parry chance, is not taking DR into effect. And I'm not sure if Hit Avoidance is supposed to have DR.

**Comment by Vishiswaz** [comment]
With Blue's
![image](https://user-images.githubusercontent.com/78314117/191790493-64fe8481-21de-4e89-a931-cd5eff8396b9.png)

With the other ones
![image](https://user-images.githubusercontent.com/78314117/191790555-9dca496b-0890-4821-8584-d37cbc6a6ee6.png)

RatingBuster predictions:
![image](https://user-images.githubusercontent.com/78314117/191790686-1a51e15d-fcaf-47c5-ad34-4a471df1b4be.png)

**Comment by raethkcj** [comment]
Apologies, all the DR calculations were set up correctly but apparently an argument to enable them in the display was missed. Fixed in master and I'll push a release shortly. Thanks for your patience debugging it.
