### ISSUE TITLE
[Feature Request] Count race expertise when considering a weapon

### ISSUE THREAD

**Issue by Vishiswaz** [raethkcj/RatingBuster#99]
It'd be nice if RatingBuster took the weapon type into consideration based on what race you are, since some races get extra expertise or whatever for certain weapon types.

For example, I'm a human using a sword, which means my racial gives me +3 expertise (not rating). When I'm considering a new weapon that's an axe, it currently doesn't tell me I'd lose 3 expertise. It really should say.

**Comment by Vishiswaz** [comment]
Just bumping this old suggestion since it'd be nice <3

**Comment by raethkcj** [comment]
Added in version 1.16.1!
